import {profitableTrips} from './profitable-trips.js?v=20261001w';
import './password-visibility.js?v=20261001t';
import {usersPage,installUsers} from './users.js?v=20261001n';
import {balancesPanel} from './balances.js?v=20261001v';
import {maintenanceFields,maintenanceValue,showMaintenance} from './maintenance-link.js?v=20261001r';
import {allExpenses,sharedCosts,costPanel,adminPage,payablePage,fuelPage,profitPage,resultData,tripMonth,installEditors,maintenancePage} from './operations.js?v=20261001v';
import {adminView,profitView,pendingHistoryView,completedTripsView} from './history.js?v=20261001f';
import {store,login,logout,restore,write,rpc,createUser} from './store.js?v=20261001z';
import {money,amounts,summarize,fuelRows} from './domain.js';
const app=document.querySelector('#app'),modal=document.querySelector('#modal');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Lima'});
let menuHidden=(localStorage.getItem('mt-menu-hidden')??String(matchMedia('(max-width:700px)').matches))==='true';
let page='Resumen',selected=null,detailTab='Servicio',month='2026-09',payFilter='pending',driverFilter='',vehicleFilter='';
const icons={Resumen:'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>',Viajes:'<path d="M3 6h11v12H3zM14 10h4l3 4v4h-7"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="19" r="2"/>',Combustible:'<path d="M4 21V4h10v17M3 21h12M6 7h6v5H6M14 9h3l3 4v6h-3v-5M17 5l4 4"/>',Cobros:'<rect x="4" y="2" width="16" height="20" rx="2"/><path d="M8 7h8M8 12h8M8 17h5"/>','Por pagar':'<rect x="2" y="5" width="20" height="15" rx="2"/><path d="M2 10h20M6 15h4"/>'};
icons['Usuarios']='<circle cx="9" cy="7" r="4"/><path d="M2 21v-3a7 7 0 0114 0v3M19 8v6M16 11h6"/>';icons['Gastos de la empresa']='<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 12h18M10 12v3h4v-3"/>';icons['Mantenimiento']='<path d="M14 3a6 6 0 00-7 8L2 16a3 3 0 004 4l5-5a6 6 0 008-7l-4 4-3-3z"/>';
const svg=n=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">'+icons[n]+'</svg>';
const data=()=>{for(const t of ['trip_costs','trip_cost_links','trip_cost_allocations','fuel_observations','administrative_details','maintenance_records','payable_accounts','payable_payments'])store.data[t]||=[];return store.data;};
const trips=()=>data().trips.map(t=>({...summarize(t,allExpenses(data()),data().customer_payments),plate:data().vehicles.find(v=>v.id===t.vehicle_id)?.plate,client_name:data().clients.find(c=>c.id===t.client_id)?.name}));
const visible=()=>trips().filter(t=>(!month||tripMonth(t)===month)&&(!driverFilter||t.driver_id===driverFilter)&&(!vehicleFilter||t.vehicle_id===vehicleFilter));
const badge=(s,c='')=>'<span class="badge '+c+'">'+esc(s)+'</span>';
const state=t=>badge(t.status==='finished'?'Viaje finalizado':'En viaje',t.status==='finished'?'green':'blue')+'<br>'+badge(t.settlement_status==='settled'?'Gastos completos':'Gastos por revisar',t.settlement_status==='settled'?'green':'amber');
const paidState=t=>badge(t.customer_balance===0?'Pagado':t.customer_paid>0?'Con abonos':'Pendiente',t.customer_balance===0?'green':'amber');
const fmt=d=>d?esc(d.slice(0,10).split('-').reverse().join('/')):'—';
const metric=(label,value,sub='')=>'<div class="metric"><small>'+label+'</small><strong>'+value+'</strong><em>'+sub+'</em></div>';
const sum=(rows,key)=>rows.reduce((s,r)=>s+Number(r[key]||0),0);
function table(headers,rows){return '<div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+ (rows.length?rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+headers.length+'" class="empty">Todavía no hay registros en esta vista.</td></tr>')+'</tbody></table></div>';}
function openButton(t){return '<button class="link" data-open="'+t.id+'">Ver viaje →</button>';}
function header(title,sub,action=''){return '<div class="page-head"><div><div class="eyebrow">MEJÍA TRANSPORT · OPERACIONES</div><h1>'+title+'</h1><p class="muted">'+sub+'</p></div><div class="actions">'+action+'</div></div>';}
const filter=()=>'<label>Mes<input aria-label="Mes" id="month" class="filter" type="month" value="'+month+'"></label>'+select('Chofer','filter-driver',[['','Todos'],...data().drivers.map(d=>[d.id,d.name])],driverFilter)+select('Unidad','filter-vehicle',[['','Todas'],...data().vehicles.map(v=>[v.id,v.plate])],vehicleFilter);
function chart(){
 const d=data(),months=[...new Set([...d.trips.map(t=>tripMonth(t)),...d.administrative_expenses.filter(e=>!e.archived_at).map(e=>e.period?.slice(0,7)),...d.expenses.map(e=>e.occurred_at?.slice(0,7)),...d.trip_costs.map(e=>e.period?.slice(0,7))])].filter(m=>m&&(!month||m<=month)).sort().slice(-6);
 const vals=months.map(m=>({m,value:resultData(d,m).result})),max=Math.max(1,...vals.map(v=>Math.abs(v.value)));
 if(!vals.length)return '<p class="muted">Aún no hay datos para mostrar la utilidad mensual.</p>';
 return '<p class="muted">Toda la empresa: después de los gastos de viajes y de empresa.</p><div class="monthly-comparison">'+vals.map(v=>'<section class="comparison-month"><div class="comparison-row"><div><span>'+esc(new Intl.DateTimeFormat('es-PE',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(v.m+'-01T12:00:00Z')))+'</span><strong'+(v.value<0?' class="danger"':'')+'>'+money(v.value)+'</strong></div><div class="comparison-track" aria-hidden="true"><span style="background:'+(v.value<0?'#b54651':'#478b7e')+';width:'+100*Math.abs(v.value)/max+'%"></span></div></div></section>').join('')+'</div><p class="muted">Se actualiza al registrar o corregir gastos. Los meses con gastos pendientes pueden cambiar; un monto negativo indica pérdida.</p>';
}
function overview(){let t=visible();let es=allExpenses(data()).filter(e=>t.some(t=>t.id===e.trip_id));let categories={};es.forEach(e=>categories[e.category]=(categories[e.category]||0)+Number(e.amount));let max=Math.max(1,...Object.values(categories));return header('Tu empresa, en un vistazo','Viajes, gastos y cobros conectados en un solo lugar.',filter())+balancesPanel(data())+profitPage(data(),month,true)+'<div class="metrics">'+metric('Viajes registrados',t.length,'En el mes seleccionado')+metric('Total por los viajes',money(sum(t,'total')),'Incluye viajes pagados y pendientes, con IGV cuando corresponde')+metric('Gastos registrados de los viajes',money(sum(t,'expenses')),'Aún faltan gastos por completar o repartir entre viajes')+'</div><div class="grid"><section class="card"><h2>Utilidad por mes</h2>'+chart()+'</section><section class="card"><h2>¿En qué se está gastando?</h2>'+Object.entries(categories).sort((a,b)=>b[1]-a[1]).map(([k,v])=>'<div class="category"><div><span>'+esc(k)+'</span><b>'+money(v)+'</b></div><div class="track"><b style="width:'+v/max*100+'%"></b></div></div>').join('')+(!es.length?'<p class="muted">Agrega gastos desde un viaje para ver el desglose.</p>':'')+'</section></div><div class="grid"><section class="card"><h2>Viajes con mayor ganancia</h2>'+profitableTable(t)+'</section><section class="card"><h2>Nuestras unidades</h2><img class="fleet-photo" src="assets/camiones.png" alt="Los dos camiones de Mejía Transport">'+data().vehicles.map(v=>'<div class="fleet-row"><div><b>'+esc(v.plate)+'</b><p class="muted">'+esc(v.description)+'</p></div>'+badge(data().trips.some(t=>t.vehicle_id===v.id&&t.status==='in_progress'&&t.settlement_status==='pending')?'Por liquidar':'Sin pendiente confirmado','blue')+'</div>').join('')+'</section></div>';}
function tripTable(t){return table(['N.º','Fecha','Viaje / unidad','Cliente y recorrido','Factura','Estado','Importe',''],t.map((t,i)=>[i+1,fmt(t.start_date),'<b>V-'+String(t.number).padStart(3,'0')+'</b><br>'+esc(t.plate),esc(t.client_name)+'<p class="muted">'+esc(t.origin)+' → '+esc(t.destination)+'</p>',esc(t.invoice_number||(t.invoice_status==='not_required'?'Sin factura':'Por emitir')),state(t),money(t.total),openButton(t)]));}
function tripList(){const rows=visible().slice().sort((a,b)=>b.start_date.localeCompare(a.start_date));const pending=rows.filter(t=>t.status!=='finished');const rest=rows.filter(t=>!pending.some(p=>p.id===t.id));return header('Viajes',rows.length+' viajes en la selección. Abre uno para revisar sus gastos, combustible y resultado.',filter()+'<button class="primary" data-action="new">+ Registrar viaje</button>')+(pending.length?'<section class="card"><h2>Viajes en curso · '+pending.length+'</h2>'+tripTable(pending)+'</section>':'')+'<section class="card"><h2>Relación de viajes realizados · '+rest.length+'</h2>'+tripTable(rest)+'</section>';}
function fuel(){const all=fuelRows(data().expenses,data().trips),rows=all.filter(e=>(!month||e.occurred_at.startsWith(month))&&(!vehicleFilter||e.vehicle_id===vehicleFilter)&&(!driverFilter||data().trips.find(t=>t.id===e.trip_id)?.driver_id===driverFilter));return header('Control de combustible','Se alimenta de los abastecimientos registrados dentro de cada viaje.',filter())+'<div class="notice">El kilometraje sigue al camión entre viajes. El rendimiento de tanque se calcula entre llenados completos; la relación por abastecimiento es orientativa.</div><div class="grid equal">'+data().vehicles.map(v=>{let r=rows.filter(e=>e.vehicle_id===v.id);return '<section class="card"><h2>'+esc(v.plate)+'</h2><div class="facts"><div><span>Galones abastecidos</span><b>'+sum(r,'gallons').toFixed(3)+' gl</b></div><div><span>Costo de combustible</span><b>'+money(sum(r,'amount'))+'</b></div><div><span>Km entre registros disponibles</span><b>'+sum(r,'distance').toFixed(1)+' km</b></div><div><span>Precio promedio por galón</span><b>'+(sum(r,'gallons')?money(sum(r,'amount')/sum(r,'gallons')):'—')+'</b></div></div></section>';}).join('')+'</div><section class="card"><h2>Historial de abastecimientos</h2>'+table(['Fecha','Unidad','Kilometraje','Km entre registros','Galones','S/ por galón','Km/gl del intervalo','Km/gl tanque lleno',''],rows.slice().reverse().map(e=>{let t=trips().find(t=>t.id===e.trip_id);return[fmt(e.occurred_at),esc(t.plate),Number(e.odometer).toLocaleString('es-PE'),e.distance??'Primer registro',Number(e.gallons).toFixed(3),money(e.price_per_gallon),e.interval_ratio?.toFixed(3)??'—',e.efficiency?.toFixed(3)??'Sin ciclo completo',openButton(t)];}))+'</section>';}
function collections(){
 const all=trips(),verified=all.filter(t=>t.collection_verified!==false);
 let rows=(payFilter==='review'?all.filter(t=>t.collection_verified===false):verified).filter(t=>payFilter==='paid'?t.customer_balance===0:payFilter==='uninvoiced'?t.invoice_status==='pending':payFilter==='review'?true:t.customer_balance>0);
 const lastPayment=t=>data().customer_payments.filter(p=>p.trip_id===t.id&&p.kind==='customer').map(p=>p.paid_on).sort().at(-1);
 rows.sort((a,b)=>(lastPayment(b)||b.start_date).localeCompare(lastPayment(a)||a.start_date));
 return header('Cobros de clientes','Cada pago actualiza el saldo del viaje y el Resumen automáticamente.')+'<div class="tabs">'+[['pending','Pendientes'],['paid','Pagadas'],['uninvoiced','Por facturar'],['review','Por verificar']].map(([k,v])=>'<button data-filter="'+k+'" class="'+(payFilter===k?'active':'')+'">'+v+'</button>').join('')+'</div>'+(payFilter==='review'?'<p class="notice">Confirma los documentos y pagos de estos servicios antes de incluirlos en el saldo por cobrar.</p>':'')+'<div class="metrics">'+metric('Clientes: saldo pendiente confirmado',money(sum(verified,'customer_balance')))+metric('Pagos recibidos · esta lista',money(sum(rows,'customer_paid')))+metric('Detracción por depositar · esta lista',money(sum(rows,'detraction_balance')))+metric('Viajes · esta lista',rows.length)+'</div><section class="card"><h2>'+({paid:'Viajes pagados',pending:'Viajes pendientes de pago',uninvoiced:'Viajes sin factura emitida',review:'Pagos por revisar'})[payFilter]+'</h2>'+table(['Operación / unidad','Factura / cliente','Importe total','Cobrado','Lo que falta cobrar','Último pago','Detracción',''],rows.map(t=>[fmt(t.billing_operation_date||t.start_date)+'<p class="muted">'+esc(t.plate)+'</p>',esc(t.invoice_number||(t.invoice_status==='not_required'?'Sin factura':'Por emitir'))+'<p class="muted">'+esc(t.client_name)+'</p>'+(t.billing_note?'<span class="badge amber">Fecha por revisar</span>':''),money(t.total),money(t.customer_paid),t.collection_verified===false?'Por verificar':money(t.customer_balance),fmt(lastPayment(t)),money(t.detraction)+'<p class="muted">'+(t.detraction_balance>0?'Pendiente '+money(t.detraction_balance):t.detraction>0?'Depositada':'No registrada')+'</p>',openButton(t)]))+'</section><p class="muted">Abre un viaje para ver sus guías, vencimiento y pagos, o registrar un abono. Pagadas significa saldo del cliente cancelado; la detracción se controla por separado.</p>';
}
function payables(){let rows=data().expenses.filter(e=>e.payment_mode==='credit').map(e=>({...e,paid:sum(data().supplier_payments.filter(p=>p.expense_id===e.id),'amount')}));return header('Pagos a proveedores','Combustible y otros gastos comprados a crédito.')+'<div class="metrics">'+metric('Saldo por pagar',money(rows.reduce((s,e)=>s+Number(e.amount)-e.paid,0)))+metric('Pagado',money(sum(rows,'paid')))+metric('Compras a crédito',rows.length)+'</div><section class="card">'+table(['Proveedor','Concepto','Unidad','Importe','Pagado','Saldo',''],rows.map(e=>{let t=trips().find(t=>t.id===e.trip_id);return[esc(e.supplier),esc(e.category),esc(t.plate),money(e.amount),money(e.paid),money(e.amount-e.paid),openButton(t)];}))+'</section>';}
function detail(){const t=trips().find(t=>t.id===selected);if(!t){selected=null;return tripList();}const es=allExpenses(data()).filter(e=>e.trip_id===t.id),ps=data().customer_payments.filter(p=>p.trip_id===t.id);let body='';if(detailTab==='Servicio')body='<div class="grid"><section class="card"><h2>Datos del servicio</h2><div class="facts">'+[['Cliente',t.client_name],['Unidad',t.plate],['Fecha de salida',fmt(t.start_date)],['Chofer',t.driver||'Por completar'],['Origen',t.origin],['Destino',t.destination],['Subtotal',money(t.subtotal)],['IGV ('+t.tax_rate+' %)',money(t.tax)],['Importe total',money(t.total)],['Fecha de término',fmt(t.end_date)]].map(([a,b])=>'<div><span>'+a+'</span><b>'+esc(b)+'</b></div>').join('')+'</div></section><section class="card result"><h2>Resultado '+(t.settlement_status==='settled'?'del viaje':'provisional')+'</h2><strong>'+money(t.operating_result)+'</strong><p class="muted">'+money(t.total)+' de servicio − '+money(t.expenses)+' de gastos.</p><hr><h3>Saldo del cliente</h3><b>'+(t.collection_verified===false?'Por verificar':money(t.customer_balance))+'</b><p class="muted">Los abonos reducen el saldo, sin modificar el resultado del viaje.</p></section></div>';
if(detailTab==='Servicio'){const pending=sharedCosts(data(),t.id).filter(c=>c.amount-c.assigned>0.000001);if(pending.length)body='<div class="notice">Hay '+pending.length+' gastos compartidos pendientes de asignación. La ganancia mostrada solo descuenta los importes asignados.</div>'+body;if(t.review_note)body='<div class="notice">'+esc(t.review_note)+'</div>'+body;}
if(detailTab==='Gastos y combustible')body=costPanel(data(),t.id)+'<section class="card"><div class="page-head"><h2>Gastos del viaje</h2><button class="primary" data-action="expense" '+(t.settlement_status==='settled'?'disabled':'')+'>+ Agregar gasto o combustible</button></div>'+table(['Fecha','Concepto','Proveedor / detalle','Importe','Pago',''],es.map(e=>[fmt(e.occurred_at),esc(e.category)+(e.gallons?'<p class="muted">'+e.gallons+' gl · '+e.odometer+' km</p>':''),esc(e.supplier||e.description||'—'),money(e.amount),badge(e.payment_mode==='unconfirmed'?'Pago por confirmar':e.payment_mode==='credit'?'A crédito':'Al contado',e.payment_mode==='credit'?'amber':'green'),(!e.cost_id?'<button data-edit-expense="'+e.id+'">Editar</button> ':'')+(e.payment_mode==='credit'?'<button class="link" data-supplier="'+e.id+'">Registrar pago</button>':'' )]))+'</section>';
if(detailTab==='Factura')body='<section class="card"><div class="page-head"><h2>Facturación del servicio</h2><button data-action="invoice">Completar / editar factura</button></div><div class="facts">'+[['Situación',({pending:'Pendiente de emitir',issued:'Facturado',not_required:'Sin factura'})[t.invoice_status]],['Número',t.invoice_number||'—'],['Emisión',fmt(t.invoice_date)],['Vencimiento',fmt(t.due_date)],['Detracción',money(t.detraction)],['Guías remitente',t.sender_guides||'—'],['Guías transporte',t.carrier_guides||'—']].map(([a,b])=>'<div><span>'+a+'</span><b>'+esc(b)+'</b></div>').join('')+'</div></section>';
if(detailTab==='Cobros')body='<div class="metrics">'+metric('Precio total del viaje',money(t.total))+metric('Recibido del cliente',money(t.customer_paid))+metric('Lo que falta cobrar',money(t.customer_balance))+metric('Detracción pendiente',money(t.detraction_balance))+'</div><section class="card"><div class="page-head"><h2>Pagos recibidos del cliente</h2><button class="primary" data-action="payment">+ Registrar pago</button></div>'+table(['Fecha','Tipo','Medio','Referencia','Importe'],ps.map(p=>[fmt(p.paid_on),p.kind==='detraction'?'Detracción':'Pago del cliente',esc(p.method),esc(p.reference||'—'),money(p.amount)]))+'</section>';
if(t.billing_note&&(detailTab==='Factura'||detailTab==='Cobros'))body='<p class="notice">'+esc(t.billing_note)+'</p>'+body;
return '<button class="link" data-action="back">← Todos los viajes</button><br><br>'+header('Viaje V-'+String(t.number).padStart(3,'0'),esc(t.plate)+' · '+esc(t.origin)+' → '+esc(t.destination),state(t)+'<button data-action="settlement">'+(t.settlement_status==='settled'?'Reabrir liquidación':'Confirmar gastos completos')+'</button><button data-edit-trip="'+t.id+'">Editar viaje</button><button data-action="close">'+(t.status==='finished'?'Reabrir viaje':'Finalizar viaje')+'</button>')+'<div class="tabs">'+['Servicio','Gastos y combustible','Factura','Cobros'].map(v=>'<button class="'+(detailTab===v?'active':'')+'" data-tab="'+v+'">'+v+'</button>').join('')+'</div>'+body;}
function render(){if(!store.user)return loginView();app.innerHTML='<div class="shell '+(menuHidden?'menu-hidden':'')+'"><aside id="main-menu"><div class="sidebar-heading"><button class="menu-toggle aside-toggle" data-toggle-menu aria-label="'+(menuHidden?'Expandir menú':'Contraer menú')+'" aria-controls="main-menu" aria-expanded="'+!menuHidden+'"><span class="toggle-line" aria-hidden="true"></span><span class="toggle-line" aria-hidden="true"></span><span class="toggle-line" aria-hidden="true"></span></button><div class="brand"><img src="assets/logo-mt-dark.png" alt="Mejía Transport S.A.C."></div></div><div class="nav-label">GESTIÓN DIARIA</div><nav class="nav">'+Object.keys(icons).filter(n=>n!=='Usuarios'||store.user.role==='admin').map(n=>'<button data-page="'+n+'" aria-label="'+n+'" title="'+n+'" class="'+(page===n?'active':'')+'">'+svg(n)+'<span class="nav-text">'+n+'</span></button>').join('')+'</nav><div class="aside-bottom"><strong>Dos unidades. Un solo control.</strong>Información de tu operación<br><br>'+ (store.demo?'Demostración local':'Gestión de transporte')+'</div></aside><main><div class="topbar"><button class="menu-toggle" data-toggle-menu aria-label="Mostrar u ocultar menú" aria-controls="main-menu" aria-expanded="'+!menuHidden+'">☰</button><span>Operaciones / '+esc(page)+'</span><div class="user">'+(store.demo?'<span class="mode">DEMOSTRACIÓN · datos de ejemplo</span>':'<span class="badge green">Sesión activa</span>')+'<span class="avatar">A</span><span>'+esc(store.user.display_name)+'</span><button class="link" data-action="logout">Salir</button></div></div><div class="content">'+(selected?detail():({Usuarios:()=>usersPage(store),Resumen:overview,Viajes:tripList,Combustible:()=>fuelPage(data(),month),Cobros:collections,'Por pagar':()=>payablePage(data()),'Gastos de la empresa':()=>adminPage(data(),month),Mantenimiento:()=>maintenancePage(data(),vehicleFilter)}[page])())+'</div></main></div>';document.querySelector('[name=filter-driver]')?.addEventListener('change',e=>{driverFilter=e.target.value;render();});document.querySelector('[name=filter-vehicle]')?.addEventListener('change',e=>{vehicleFilter=e.target.value;render();});document.querySelector('#month')?.addEventListener('change',e=>{month=e.target.value;render();});}
function loginView(){app.innerHTML='<div class="login"><section class="login-art"><div><img class="login-hero-logo" src="assets/logo-mt-dark.png" alt="MEJÍA TRANSPORT S.A.C."><div class="login-brand-name">MEJÍA TRANSPORT S.A.C.</div><h1>El control de tu empresa.<br>En un solo lugar.</h1><p>Tu flota, tus viajes y tus resultados.</p></div></section><section class="login-panel"><div><img class="login-logo" src="assets/logo-mt-dark.png" alt="Mejía Transport S.A.C."><div class="eyebrow">GESTIÓN DE TRANSPORTE</div><h1>Bienvenido</h1><p class="muted">Ingresa para gestionar tu empresa.</p><br><form id="login"><label>Usuario<input name="email" type="text" placeholder="amejia" autocomplete="username" required></label><label>Contraseña<input name="password" type="password" autocomplete="current-password" required></label><p class="error" id="login-error"></p><button class="primary">Ingresar</button></form><p class="footnote">Acceso exclusivo del equipo de Mejía Transport S.A.C.</p></div></section></div>';document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const f=new FormData(e.target);await login(f.get('email'),f.get('password'));page='Resumen';render();}catch(err){document.querySelector('#login-error').textContent=err.message;}finally{b.disabled=false;}};}
const input=(label,name,type='text',value='',extra='')=>'<label>'+label+'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'" '+extra+'></label>';
const select=(label,name,options,value)=>'<label>'+label+'<select name="'+name+'">'+options.map(([k,v])=>'<option value="'+k+'" '+(k===value?'selected':'')+'>'+esc(v)+'</option>').join('')+'</select></label>';
function form(title,fields,onSave){modal.innerHTML='<div class="dialog-title"><h2>'+title+'</h2><button type="button" id="dismiss" aria-label="Cerrar">×</button></div><form><div class="form-grid">'+fields+'</div><p class="error" id="form-error"></p><div class="form-actions"><button type="button" id="cancel">Cancelar</button><button class="primary">Guardar</button></div></form>';modal.showModal();modal.querySelector('#dismiss').onclick=modal.querySelector('#cancel').onclick=()=>modal.close();modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button.primary');b.disabled=true;try{await onSave(Object.fromEntries(new FormData(e.target)));modal.close();render();toast('Registro guardado');}catch(err){modal.querySelector('#form-error').textContent=err.message;}finally{b.disabled=false;}};}
function newTrip(){form('Registrar viaje',select('Unidad','vehicle_id',data().vehicles.map(v=>[v.id,v.plate]))+input('Fecha de salida','start_date','date',today(),'required')+input('Cliente','client','text','','required list="clients"')+'<datalist id="clients">'+data().clients.map(c=>'<option value="'+esc(c.name)+'">').join('')+'</datalist>'+select('Chofer','driver_id',data().drivers.map(d=>[d.id,d.name]),data().vehicles[0]?.default_driver_id)+input('Origen','origin','text','','required')+input('Destino','destination','text','','required')+select('El importe ingresado es','mode',[['total','Total con IGV incluido'],['subtotal','Subtotal antes de IGV']],'total')+input('Importe (S/)','value','number','','min="0.01" step="0.01" required')+select('IGV aplicable','rate',[['18','18 %'],['0','0 %']],'18')+select('Facturación prevista','invoice_status',[['pending','Se emitirá factura después'],['not_required','Servicio sin factura']],'pending')+'<div class="notice full" id="calc">Ingresa el importe para calcular el desglose.</div>',async f=>{let client=data().clients.find(c=>c.name.trim().toLowerCase()===f.client.trim().toLowerCase());if(!client)client=await write('clients',{name:f.client.trim()});const a=amounts(f.value,f.rate,f.mode);const t=await write('trips',{vehicle_id:f.vehicle_id,client_id:client.id,start_date:f.start_date,origin:f.origin.trim(),destination:f.destination.trim(),driver_id:f.driver_id,driver:data().drivers.find(d=>d.id===f.driver_id)?.name,subtotal:a.subtotal,tax_rate:Number(f.rate),invoice_status:f.invoice_status,detraction:0});selected=t.id;page='Viajes';detailTab='Servicio';});const calc=()=>{let f=Object.fromEntries(new FormData(modal.querySelector('form'))),a=amounts(f.value,f.rate,f.mode);modal.querySelector('#calc').textContent='Subtotal '+money(a.subtotal)+' + IGV '+money(a.tax)+' = Total '+money(a.total);};modal.querySelector('form').oninput=calc;modal.querySelector('[name=vehicle_id]').onchange=e=>{const v=data().vehicles.find(v=>v.id===e.target.value);if(v.default_driver_id)modal.querySelector('[name=driver_id]').value=v.default_driver_id;};}
function expense(id){const existing=typeof id==='string'?data().expenses.find(e=>e.id===id):null;form(existing?'Editar gasto del viaje':'Agregar gasto al viaje',select('Concepto','category',['Combustible','Peajes','Viáticos','Estiba','Desestiba','Encarpado','Cochera','Comisión','Reparación','Repuestos','Otros'].map(v=>[v,v]),'Combustible')+input('Fecha y hora (Perú)','occurred_at','datetime-local',today()+'T12:00','required')+input('Monto total (S/)','amount','number','','step="0.01" min="0.01" required')+select('Pago','payment_mode',[['cash','Al contado'],['credit','A crédito']],'cash')+input('Proveedor / grifo','supplier')+input('Detalle','description')+'<div class="full form-grid" id="fuel-fields">'+input('Kilometraje al abastecer','odometer','number','','min="0" step="0.1" required')+input('Galones abastecidos','gallons','number','','min="0.001" step="0.001" required')+select('¿Quedó el tanque lleno?','full_tank',[['','No confirmado'],['true','Sí, tanque lleno'],['false','No, carga parcial']],'')+input('Nota de venta','receipt')+'</div>'+input('Factura del proveedor (opcional)','invoice_number')+input('Vencimiento si es a crédito','due_date','date')+maintenanceFields(input,existing?.maintenance,'',existing?new Date(new Date(existing.occurred_at).getTime()-5*3600000).toISOString().slice(0,10):today()),async f=>{let fuel=f.category==='Combustible';await write('expenses',{trip_id:existing?.trip_id||selected,category:f.category,occurred_at:f.occurred_at+':00-05:00',amount:Number(f.amount),payment_mode:f.payment_mode,supplier:f.supplier||null,description:f.description,odometer:fuel?Number(f.odometer):null,gallons:fuel?Number(f.gallons):null,full_tank:fuel&&f.full_tank!==''?f.full_tank==='true':null,receipt:f.receipt||null,invoice_number:f.invoice_number||null,due_date:f.due_date||null,maintenance:maintenanceValue(f,'',f.occurred_at.slice(0,10))},existing?.id);});modal.querySelector('[name=category]').onchange=e=>{showMaintenance(modal,e.target.value);const fuel=e.target.value==='Combustible',box=modal.querySelector('#fuel-fields');box.hidden=!fuel;box.style.display=fuel?'grid':'none';box.querySelectorAll('input,select').forEach(x=>{x.disabled=!fuel;});};modal.querySelector('[name=payment_mode]').onchange=e=>modal.querySelector('[name=supplier]').required=e.target.value==='credit';showMaintenance(modal,'Combustible');if(existing){for(const [key,value] of Object.entries(existing)){const field=modal.querySelector('[name="'+key+'"]');if(field)field.value=value??'';}modal.querySelector('[name=occurred_at]').value=new Date(new Date(existing.occurred_at).getTime()-5*3600000).toISOString().slice(0,16);modal.querySelector('[name=category]').dispatchEvent(new Event('change'));modal.querySelector('[name=payment_mode]').dispatchEvent(new Event('change'));}}
function invoice(){const t=trips().find(t=>t.id===selected);form('Factura y documentos',select('Situación','invoice_status',[['pending','Pendiente de emitir'],['issued','Factura emitida'],['not_required','Sin factura']],t.invoice_status)+input('Número de factura','invoice_number','text',t.invoice_number)+input('Fecha de emisión','invoice_date','date',t.invoice_date)+input('Vencimiento','due_date','date',t.due_date)+input('Detracción prevista (S/)','detraction','number',t.detraction,'min="0" step="0.01" required')+input('Guías remitente','sender_guides','text',t.sender_guides)+input('Guías transporte','carrier_guides','text',t.carrier_guides)+input('Enlace de documentos en Drive','drive_url','url',t.drive_url)+select('¿Ya verificaste todos los pagos de este servicio?','collection_verified',[['false','No, saldo por verificar'],['true','Sí, incluir saldo confirmado']],String(t.collection_verified!==false))+'<p class="notice full">Registra primero los pagos ya recibidos. Al confirmar, el saldo restante se incluirá en Por cobrar.</p>',async f=>write('trips',{...f,collection_verified:f.collection_verified==='true',invoice_number:f.invoice_status==='issued'?f.invoice_number.trim():null,invoice_date:f.invoice_status==='issued'?f.invoice_date||null:null,due_date:f.due_date||null,detraction:Number(f.detraction)},selected));}
function payment(expenseId){const t=trips().find(t=>t.id===selected);const e=data().expenses.find(e=>e.id===expenseId);form(e?'Registrar pago al proveedor':'Registrar pago del cliente',(!e?select('Tipo de pago','kind',[['customer','Pago del cliente (parcial o total)'],['detraction','Depósito de detracción']],'customer'):'<div class="notice full">'+esc(e.supplier)+' · Saldo '+money(e.amount-sum(data().supplier_payments.filter(p=>p.expense_id===e.id),'amount'))+'</div>')+input('Fecha de pago','paid_on','date',today(),'required')+input('Importe (S/)','amount','number','','min="0.01" step="0.01" required')+select('Medio de pago','method',[['Transferencia','Transferencia'],['Efectivo','Efectivo'],['Depósito','Depósito']],'Transferencia')+input('Referencia / operación','reference'),async f=>write(e?'supplier_payments':'customer_payments',{...f,amount:Number(f.amount),...(e?{expense_id:e.id}:{trip_id:t.id})}));}
function adminExpense(){form('Registrar gasto administrativo',input('Fecha del gasto','incurred_on','date',today(),'required')+select('Categoría','category',['Sueldos','Contador','Seguros','GPS','Oficina','Impuestos','Reparaciones generales','Otros'].map(v=>[v,v]),'Otros')+input('Concepto','description','text','','required')+input('Importe (S/)','amount','number','','min="0.01" step="0.01" required')+input('Comprobante en Drive','drive_url','url'),f=>write('administrative_expenses',{...f,amount:Number(f.amount)}));}
function closeTrip(){let t=trips().find(t=>t.id===selected);if(t.status==='finished'){form('Reabrir viaje','<div class="notice full">El viaje volverá a estar en curso y sus gastos quedarán por revisar. La factura y los pagos se conservan.</div>',()=>write('trips',{status:'in_progress',settlement_status:'review',end_date:null},t.id));return;}form('Finalizar viaje',input('Fecha de término (si la conoces)','end_date','date','','min="'+t.start_date+'"')+'<div class="notice full">Marca que terminó el traslado. Puedes completar los gastos, emitir la factura y registrar sus pagos después.</div>',f=>write('trips',{status:'finished',end_date:f.end_date||null},t.id));}
function settlement(){const t=trips().find(t=>t.id===selected);if(t.settlement_status==='settled'){form('Reabrir liquidación','<p>Podrás corregir los gastos. La factura y los pagos se conservan.</p>',()=>write('trips',{settlement_status:'review'},t.id));return;}if(t.status!=='finished'){toast('Primero marca el viaje como finalizado.');return;}form('Confirmar gastos completos','<p>Confirma que registraste y revisaste todos los gastos de este viaje. Su ganancia se incluirá en el ranking.</p>',()=>write('trips',{settlement_status:'settled'},t.id));}
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.style.display='block';setTimeout(()=>t.style.display='none',3500);}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;try{if(b.hasAttribute('data-toggle-menu')){menuHidden=!menuHidden;localStorage.setItem('mt-menu-hidden',String(menuHidden));document.querySelector('.shell').classList.toggle('menu-hidden',menuHidden);document.querySelectorAll('[data-toggle-menu]').forEach(el=>{el.setAttribute('aria-expanded',String(!menuHidden));el.setAttribute('aria-label',menuHidden?'Expandir menú':'Contraer menú');});return;}if(b.dataset.page){page=b.dataset.page;selected=null;render();}if(b.dataset.open){selected=b.dataset.open;page='Viajes';detailTab='Servicio';render();}if(b.dataset.tab){detailTab=b.dataset.tab;render();}if(b.dataset.filter){payFilter=b.dataset.filter;render();}if(b.dataset.supplier)payment(b.dataset.supplier);if(b.dataset.editExpense)expense(b.dataset.editExpense);const actions={admin:adminExpense,new:newTrip,expense,invoice,payment:()=>payment(),close:closeTrip,settlement,back:()=>{selected=null;render();},logout:()=>{logout();selected=null;render();}};if(b.dataset.action)actions[b.dataset.action]?.();}catch(err){toast(err.message);}});
installEditors({data,form,input,select,write,rpc,render,selected:()=>selected,month:()=>month,today});
try{await restore();}catch(err){toast(err.message);}render();


installUsers({store,form,input,createUser});

function profitableTable(rows){
 const ranked=profitableTrips(rows,t=>sharedCosts(data(),t.id).some(c=>Number(c.amount)-c.assigned>0.005));
 return '<p class="muted">Los 5 viajes con mayor ganancia de la selección. Total del viaje menos todos sus gastos. Solo liquidaciones completas; gastos de empresa aparte.</p>'+ (ranked.length?table(['Puesto','Fecha / unidad','Cliente y recorrido','Total del viaje','Gastos del viaje','Ganancia del viaje',''],ranked.map((t,i)=>[i+1,fmt(t.start_date)+'<p class="muted">'+esc(t.plate)+'</p>',esc(t.client_name)+'<p class="muted">'+esc(t.origin)+' → '+esc(t.destination)+'</p>',money(t.total),money(t.expenses),'<strong>'+money(t.operating_result)+'</strong>',openButton(t)])):'<p class="empty">Aún no hay viajes con liquidación completa en esta selección. Completa sus gastos y pulsa Confirmar gastos completos dentro del viaje.</p>');
}
