const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const scopes={company:'Empresa y personal',a3k:'Volvo rojo · A3K-853 + TJI-995',f2h:'International blanco · F2H-732 + BVC-977'};
let scope='all',filter='active';
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Lima'});
export function documentStatus(d,now=today()){
 if(d.archived)return {label:'Archivado',tone:'muted',order:5};
 if(d.expiry_kind==='unknown')return {label:'Fecha por revisar',tone:'amber',order:2};
 if(!d.expires_on)return {label:d.expiry_kind==='bundle'?'Contiene varios documentos':'Sin vencimiento indicado',tone:'blue',order:4};
 const days=Math.round((Date.parse(d.expires_on+'T00:00:00Z')-Date.parse(now+'T00:00:00Z'))/86400000);
 return days<0?{label:'Vencido hace '+(-days)+' días',tone:'red',order:0,days}:days===0?{label:'Vence hoy',tone:'red',order:0,days}:days<=30?{label:'Vence en '+days+' días',tone:'red',order:1,days}:{label:'Vigente · '+days+' días',tone:'green',order:3,days};
}
const date=d=>d?d.split('-').reverse().join('/'):'—';
export function documentsPage(d){
 const all=d.company_documents||[],active=all.filter(d=>!d.archived),expired=active.filter(d=>documentStatus(d).days<0),soon=active.filter(d=>{const s=documentStatus(d);return s.days>=0&&s.days<=30;});
 let rows=all.filter(d=>(scope==='all'||d.scope===scope)&&(filter==='archived'?d.archived:filter==='alerts'?documentStatus(d).order<2:filter==='review'?d.expiry_kind==='unknown'&&!d.archived:!d.archived));
 rows.sort((a,b)=>documentStatus(a).order-documentStatus(b).order||(a.expires_on||'9999').localeCompare(b.expires_on||'9999')||a.title.localeCompare(b.title));
 const metric=(label,n,key)=>'<button class="metric" data-doc-filter="'+key+'"><small>'+label+'</small><strong>'+n+'</strong></button>';
 return '<div class="page-head"><div><div class="eyebrow">CONTROL DOCUMENTARIO</div><h1>Documentos de empresa</h1><p class="muted">Tus documentos siguen en Drive. Aquí controlas cuándo renovarlos.</p></div><button class="primary" data-document-new>+ Agregar documento</button></div><div class="metrics">'+metric('Documentos activos',active.length,'active')+metric('Vencidos',expired.length,'alerts')+metric('Vencen en 30 días',soon.length,'alerts')+metric('Fechas por revisar',active.filter(d=>d.expiry_kind==='unknown').length,'review')+'</div><div class="tabs">'+[['all','Todos'],...Object.entries(scopes)].map(([k,v])=>'<button data-doc-scope="'+k+'" class="'+(scope===k?'active':'')+'">'+v+'</button>').join('')+'</div><div class="actions">'+[['active','Activos'],['alerts','Alertas'],['review','Por revisar'],['archived','Copias y anteriores']].map(([k,v])=>'<button data-doc-filter="'+k+'" class="'+(filter===k?'primary':'')+'">'+v+'</button>').join('')+'</div><p class="muted">Plataforma azul TJI-995 con Volvo rojo. Plataforma roja BVC-977 con International blanco. Al renovar un documento, actualiza su fecha y enlace. Alertas calculadas cada día.</p><div class="document-grid">'+rows.map(doc=>{const s=documentStatus(doc);return '<article class="card document-card"><div class="document-status"><span class="badge '+s.tone+'">'+s.label+'</span><small>'+esc(doc.equipment||doc.person||'Empresa')+'</small></div><h2><a href="'+esc(doc.drive_url)+'" target="_blank" rel="noopener noreferrer">'+esc(doc.title.replace(/\.pdf$/i,''))+' ↗</a></h2><p class="muted">'+esc(scopes[doc.scope])+(doc.person?' · '+esc(doc.person):'')+'</p><div class="document-expiry"><small>Vencimiento</small><strong>'+date(doc.expires_on)+'</strong></div>'+(doc.notes?'<p class="muted">'+esc(doc.notes)+'</p>':'')+'<div class="actions"><a class="document-open" href="'+esc(doc.drive_url)+'" target="_blank" rel="noopener noreferrer">Abrir en Drive ↗</a><button data-document-edit="'+doc.id+'">Editar</button><button data-document-archive="'+doc.id+'">'+(doc.archived?'Recuperar':'Archivar')+'</button></div></article>';}).join('')+'</div>'+(!rows.length?'<p class="empty">No hay documentos en esta selección.</p>':'');
}
export function installDocuments({data,render,form,input,select,write}){document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.docScope){scope=b.dataset.docScope;render();}if(b.dataset.docFilter){filter=b.dataset.docFilter;render();}const rows=data().company_documents||[];
 if(b.hasAttribute('data-document-new')||b.dataset.documentEdit){const old=rows.find(d=>d.id===b.dataset.documentEdit);form(old?'Editar documento':'Agregar documento',input('Nombre del documento','title','text',old?.title||'','required')+select('Unidad / grupo','scope',Object.entries(scopes),old?.scope||'company')+input('Placa o equipo (opcional)','equipment','text',old?.equipment||'')+input('Persona (opcional)','person','text',old?.person||'')+input('Enlace del documento en Drive','drive_url','url',old?.drive_url||'','required')+select('Fecha de vencimiento','expiry_kind',[['dated','Tiene fecha de vencimiento'],['not_stated','El documento no indica vencimiento'],['unknown','Falta revisar la fecha'],['bundle','PDF con varios documentos']],old?.expiry_kind||'dated')+input('Vence el','expires_on','date',old?.expires_on||'')+input('Observaciones','notes','text',old?.notes||''),f=>{const url=new URL(f.drive_url);if(url.protocol!=='https:'||url.hostname!=='drive.google.com')throw Error('Usa el enlace del archivo en Google Drive.');if(f.expiry_kind==='dated'&&!f.expires_on)throw Error('Completa el vencimiento.');return write('company_documents',{...f,expires_on:f.expiry_kind==='dated'?f.expires_on:null,checked_on:today()},old?.id);});}
 if(b.dataset.documentArchive){const old=rows.find(d=>d.id===b.dataset.documentArchive);form(old.archived?'Recuperar documento':'Archivar documento','<p>El PDF se conserva en Drive. '+(old.archived?'Volverá a aparecer entre los documentos activos.':'Quedará en Copias y anteriores, sin generar alertas.')+'</p>',()=>write('company_documents',{archived:!old.archived},old.id));}
 });}
