const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase().trim();
const date=d=>d?d.slice(0,10).split('-').reverse().join('/'):'—';
const plates={'F2H-732':'International blanco','A3K-853':'Volvo rojo','BVC-977':'Plataforma roja · enganchada al F2H-732','TJI-995':'Plataforma azul · enganchada al A3K-853'};
export function documentOwner(doc,data){
 if(doc.person==='Todos los choferes')return {key:'shared',category:'drivers',label:'Documentos compartidos de los choferes',description:'Seguros y constancias que incluyen a ambos conductores.'};
 if(doc.person){const driver=(data.drivers||[]).find(d=>norm(d.name)===norm(doc.person));return {key:'person:'+doc.person,category:driver?'drivers':'company',label:driver?.name||doc.person,description:driver?'Documentos del chofer':'Documentos del personal administrativo'};}
 if(doc.equipment)return {key:'unit:'+doc.equipment,category:'units',label:doc.equipment,description:plates[doc.equipment]||(data.vehicles||[]).find(v=>v.plate===doc.equipment)?.description||'Documentos de la unidad'};
 return {key:'company',category:'company',label:'Mejía Transport S.A.C.',description:'Documentos de la empresa, contratos y formatos.'};
}
const rank=d=>{const t=norm(d.title);return /^dni\b/.test(t)?0:/licencia.*a3/.test(t)?1:/licencia.*a4/.test(t)?2:/soat/.test(t)?3:/revisi/.test(t)?4:/contrato/.test(t)?5:/laboral|^cul/.test(t)?6:/emo|salvador emerson/.test(t)?7:/curso/.test(t)?8:10;};
function listing(rows,status){return '<div class="document-table-wrap"><table class="document-table"><thead><tr><th>N.º</th><th>Documento</th><th>Vencimiento</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>'+[...rows].sort((a,b)=>rank(a)-rank(b)||a.title.localeCompare(b.title)).map((doc,i)=>{const s=status(doc);return '<tr><td>'+(i+1)+'</td><td><strong>'+esc(doc.title.replace(/\.pdf$/i,''))+'</strong>'+(doc.notes?'<details class="document-notes"><summary>Ver observaciones</summary><p>'+esc(doc.notes)+'</p></details>':'')+'</td><td class="document-date">'+date(doc.expires_on)+'</td><td><span class="badge '+s.tone+'">'+s.label+'</span></td><td><div class="document-row-actions"><a href="'+esc(doc.drive_url)+'" target="_blank" rel="noopener noreferrer">Abrir en Drive ↗</a><button data-document-edit="'+esc(doc.id)+'">Editar</button><button data-document-archive="'+esc(doc.id)+'">'+(doc.archived?'Recuperar':'Archivar')+'</button></div></td></tr>';}).join('')+'</tbody></table></div>';}
export function documentLayout(data,{category,owner,filter,status}){
 const all=data.company_documents||[],items=all.filter(d=>documentOwner(d,data).category===category),groups=new Map();
 for(const doc of items){const g=documentOwner(doc,data);if(!groups.has(g.key))groups.set(g.key,{...g,rows:[]});groups.get(g.key).rows.push(doc);}
 const ordered=[...groups.values()].sort((a,b)=>(a.key==='shared')-(b.key==='shared')||a.label.localeCompare(b.label));
 const active=items.filter(d=>!d.archived&&(owner==='all'||documentOwner(d,data).key===owner));
 const metric=(label,n,key)=>'<button class="metric" data-doc-filter="'+key+'"><small>'+label+'</small><strong>'+n+'</strong></button>';
 const matches=d=>filter==='archived'?d.archived:!d.archived&&(filter==='alerts'?status(d).order<2:filter==='review'?d.expiry_kind==='unknown':true);
 const lists=ordered.filter(g=>owner==='all'||owner===g.key).map(g=>({...g,rows:g.rows.filter(matches)})).filter(g=>g.rows.length);
 return '<div class="page-head"><div><div class="eyebrow">CONTROL DOCUMENTARIO</div><h1>Documentos de empresa</h1><p class="muted">Elige un chofer o una unidad para consultar su listado de documentos.</p></div><button class="primary" data-document-new>+ Agregar documento</button></div><div class="tabs document-categories">'+[['drivers','Choferes'],['units','Unidades'],['company','Empresa']].map(([key,label])=>'<button data-doc-category="'+key+'" class="'+(category===key?'active':'')+'">'+label+'</button>').join('')+'</div><div class="document-owners"><button data-doc-owner="all" class="'+(owner==='all'?'primary':'')+'">'+(category==='drivers'?'Todos los choferes':category==='units'?'Todas las unidades':'Todos')+'</button>'+ordered.map(g=>'<button data-doc-owner="'+esc(g.key)+'" class="'+(owner===g.key?'primary':'')+'">'+esc(g.key==='shared'?'Compartidos':g.label)+' <small>('+g.rows.filter(d=>!d.archived).length+')</small></button>').join('')+'</div><div class="metrics document-metrics">'+metric('Documentos activos',active.length,'active')+metric('Vencidos',active.filter(d=>status(d).days<0).length,'alerts')+metric('Vencen en 30 días',active.filter(d=>{const s=status(d);return s.days>=0&&s.days<=30;}).length,'alerts')+metric('Fechas por revisar',active.filter(d=>d.expiry_kind==='unknown').length,'review')+'</div><div class="actions document-filters">'+[['active','Activos'],['alerts','Alertas'],['review','Por revisar'],['archived','Copias y anteriores']].map(([key,label])=>'<button data-doc-filter="'+key+'" class="'+(filter===key?'primary':'')+'">'+label+'</button>').join('')+'</div>'+lists.map(g=>'<section class="card document-group"><div class="page-head"><div><h2>'+esc(g.label)+'</h2><p class="muted">'+esc(g.description)+'</p></div><span class="badge blue">'+g.rows.length+' documentos</span></div>'+listing(g.rows,status)+'</section>').join('')+(!lists.length?'<section class="card"><p class="empty">No hay documentos en esta selección.</p></section>':'')+'<p class="muted">Los archivos siguen en Drive. Al renovarlos, actualiza su fecha y enlace. Solo se muestran vencimientos confirmados en el documento.</p>';
}
export function documentOwners(data,old){
 const choices=[{key:'company',label:'Empresa',scope:'company',person:null,equipment:null},{key:'shared',label:'Choferes · documento compartido',scope:'company',person:'Todos los choferes',equipment:null},...(data.drivers||[]).map(d=>({key:'person:'+d.name,label:'Chofer · '+d.name,scope:'company',person:d.name,equipment:null}))];
 for(const plate of new Set([...(data.vehicles||[]).map(v=>v.plate),...Object.keys(plates)]))choices.push({key:'unit:'+plate,label:'Unidad · '+plate+' · '+(plates[plate]||''),scope:['A3K-853','TJI-995'].includes(plate)?'a3k':['F2H-732','BVC-977'].includes(plate)?'f2h':'company',person:null,equipment:plate});
 if(old){const g=documentOwner(old,data);if(!choices.some(c=>c.key===g.key))choices.push({key:g.key,label:g.label,scope:old.scope,person:old.person||null,equipment:old.equipment||null});}
 return choices;
}
