const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
import {documentOwner,documentLayout,documentOwners} from './document-layout.js?v=20261001zg';
let category='drivers',owner='all',filter='active';
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Lima'});
export function documentStatus(d,now=today()){
 if(d.archived)return {label:'Archivado',tone:'muted',order:5};
 if(d.expiry_kind==='unknown')return {label:'Fecha por revisar',tone:'amber',order:2};
 if(!d.expires_on)return {label:d.expiry_kind==='bundle'?'Contiene varios documentos':'Sin vencimiento indicado',tone:'blue',order:4};
 const days=Math.round((Date.parse(d.expires_on.slice(0,10)+'T00:00:00Z')-Date.parse(now+'T00:00:00Z'))/86400000);
 return days<0?{label:'Vencido',tone:'red',order:0,days}:days===0?{label:'Vence hoy',tone:'red',order:0,days}:days<=30?{label:'Vence en '+days+(days===1?' día':' días'),tone:'red',order:1,days}:{label:'Vigente',tone:'green',order:3,days};
}
const date=d=>d?d.split('-').reverse().join('/'):'—';
export function documentsPage(d){return documentLayout(d,{category,owner,filter,status:documentStatus});}
export function installDocuments({data,render,form,input,select,write}){document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.docCategory){category=b.dataset.docCategory;owner='all';filter='active';render();}if(b.dataset.docOwner){owner=b.dataset.docOwner;render();}if(b.dataset.docFilter){filter=b.dataset.docFilter;render();}const rows=data().company_documents||[];
 if(b.hasAttribute('data-document-new')||b.dataset.documentEdit){const old=rows.find(d=>d.id===b.dataset.documentEdit),choices=documentOwners(data(),old);form(old?'Editar documento':'Agregar documento',input('Nombre del documento','title','text',old?.title||'','required')+select('¿De quién es este documento?','owner',choices.map(c=>[c.key,c.label]),old?documentOwner(old,data()).key:owner==='all'?'company':owner)+input('Enlace del documento en Drive','drive_url','url',old?.drive_url||'','required')+select('Fecha de vencimiento','expiry_kind',[['dated','Tiene fecha de vencimiento'],['not_stated','El documento no indica vencimiento'],['unknown','Falta revisar la fecha'],['bundle','PDF con varios documentos']],old?.expiry_kind||'dated')+input('Vence el','expires_on','date',old?.expires_on||'')+input('Observaciones','notes','text',old?.notes||''),f=>{const url=new URL(f.drive_url);if(url.protocol!=='https:'||url.hostname!=='drive.google.com')throw Error('Usa el enlace del archivo en Google Drive.');if(f.expiry_kind==='dated'&&!f.expires_on)throw Error('Completa el vencimiento.');const selected=choices.find(c=>c.key===f.owner);if(!selected)throw Error('Selecciona a quién pertenece el documento.');const {owner:ignored,...values}=f;return write('company_documents',{...values,scope:selected.scope,person:selected.person,equipment:selected.equipment,expires_on:f.expiry_kind==='dated'?f.expires_on:null,checked_on:today()},old?.id);});}
 if(b.dataset.documentArchive){const old=rows.find(d=>d.id===b.dataset.documentArchive);form(old.archived?'Recuperar documento':'Archivar documento','<p>El PDF se conserva en Drive. '+(old.archived?'Volverá a aparecer entre los documentos activos.':'Quedará en Copias y anteriores, sin generar alertas.')+'</p>',()=>write('company_documents',{archived:!old.archived},old.id));}
 });}
