import {money,round} from './domain.js?v=20261005b';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function driverCashBalance(d,id){
 const movements=(d.driver_cash_entries||[]).filter(e=>e.trip_id===id&&!e.voided);
 const expenses=[...d.expenses.filter(e=>e.trip_id===id).map(e=>({...e,source:'expense',description:e.description||e.category})),...d.trip_cost_allocations.filter(e=>e.trip_id===id&&Number(e.amount)>0).map(e=>({...e,source:'allocation',description:d.trip_costs.find(c=>c.id===e.cost_id)?.description||'Gasto del viaje'}))];
 const total=kind=>round(movements.filter(e=>e.kind===kind).reduce((s,e)=>s+Number(e.amount),0));
 const spent=round(expenses.filter(e=>e.driver_paid===true).reduce((s,e)=>s+Number(e.amount),0));
 const delivered=total('delivery'),returned=total('return');
 return {movements,expenses,delivered,returned,spent,balance:round(delivered-returned-spent),unknown:expenses.filter(e=>e.driver_paid==null&&e.payment_mode!=='credit').length};
}
export function driverCashPanel(d,t,table){
 const b=driverCashBalance(d,t.id),card=(label,n)=>'<div class="metric"><small>'+label+'</small><strong>'+money(n)+'</strong></div>';
 return '<section class="card"><div class="page-head"><h2>Dinero del chofer</h2><div class="actions"><button class="primary" data-cash-new="delivery">+ Entregar dinero</button><button data-cash-new="return">Registrar devolución</button></div></div><p class="muted">Registra aquí el dinero que entregas para el viaje, incluidos adelantos y reembolsos. El gasto se descuenta una sola vez, cuando registras en qué se usó.</p><div class="metrics">'+card('Entregado al chofer',b.delivered)+card('Gastado por el chofer',b.spent)+card('Devuelto a la empresa',b.returned)+card(b.balance>=0?'Saldo por devolver':'Falta reembolsar al chofer',Math.abs(b.balance))+'</div>'+(t.settlement_status!=='settled'?'<p class="muted">Saldo provisional hasta completar los gastos del viaje.</p>':'')+(b.unknown?'<p class="notice">Hay '+b.unknown+' gastos sin confirmar quién los pagó. El saldo es provisional.</p>':'')+table(['Fecha','Chofer','Movimiento','Monto','Medio / operación','Detalle',''],b.movements.map(e=>[esc(e.paid_on),esc(d.drivers.find(x=>x.id===e.driver_id)?.name),e.kind==='delivery'?'Entrega al chofer':'Devolución del chofer',money(e.amount),esc(e.method)+'<br>'+esc(e.reference),esc(e.notes),'<button data-cash-edit="'+e.id+'">Editar</button> <button data-cash-void="'+e.id+'">Eliminar</button>']))+'</section><section class="card"><h2>¿Quién pagó cada gasto?</h2><p class="muted">Marca los gastos de la liquidación pagados por el chofer, incluido lo que puso de su bolsillo. Los gastos a crédito no se descuentan del dinero entregado.</p>'+table(['Gasto','Monto','Pagado por',''],b.expenses.map(e=>[esc(e.description),money(e.amount),e.payment_mode==='credit'?'A crédito':e.driver_paid===true?'Chofer':e.driver_paid===false?'Empresa':'Por confirmar',e.payment_mode==='credit'?'':'<button data-cash-payer="'+e.id+'" data-cash-source="'+e.source+'">Elegir / cambiar</button>']))+'</section>';
}
export function installDriverCash({data,selected,form,input,select,write,rpc,today}){
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=data(),trip=selected();
 if(b.dataset.cashNew||b.dataset.cashEdit){const old=d.driver_cash_entries?.find(x=>x.id===b.dataset.cashEdit),t=d.trips.find(x=>x.id===trip),kind=old?.kind||b.dataset.cashNew;
 form(old?'Editar movimiento':kind==='delivery'?'Entregar dinero al chofer':'Registrar devolución del chofer',select('Chofer','driver_id',[['','Selecciona el chofer'],...d.drivers.map(x=>[x.id,x.name])],old?.driver_id||t.driver_id||'')+input('Fecha','paid_on','date',old?.paid_on||today(),'required')+input('Monto (S/)','amount','number',old?.amount||'','required min="0.01" step="0.01"')+select('Medio de pago','method',['Efectivo','Transferencia','Depósito'].map(x=>[x,x]),old?.method||'Efectivo')+input('Número de operación (opcional)','reference','text',old?.reference||'')+input('Detalle (opcional)','notes','text',old?.notes||''),f=>{if(!f.driver_id)throw Error('Selecciona el chofer que recibe o devuelve el dinero.');return write('driver_cash_entries',{...f,kind,trip_id:trip,amount:Number(f.amount)},old?.id);});
 }
 if(b.dataset.cashVoid){const old=d.driver_cash_entries.find(x=>x.id===b.dataset.cashVoid);form('Eliminar movimiento','<p>Se anulará este movimiento de '+money(old.amount)+'. El saldo del chofer se recalculará.</p>',()=>write('driver_cash_entries',{voided:true},old.id));}
 if(b.dataset.cashPayer){const source=b.dataset.cashSource,id=b.dataset.cashPayer,old=(source==='expense'?d.expenses:d.trip_cost_allocations).find(x=>x.id===id);form('Quién pagó el gasto',select('Pagado por','payer',[['','Por confirmar'],['driver','Chofer'],['company','Empresa']],old.driver_paid===true?'driver':old.driver_paid===false?'company':''),f=>rpc('mt_driver_payer',{p_expense:source==='expense'?id:null,p_allocation:source==='allocation'?id:null,p_driver:f.payer===''?null:f.payer==='driver'}));}
 });
}
