import {money,amounts} from './domain.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const months=['ENERO','FEBRERO','MARZO','ABRIL','MAYO','JUNIO','JULIO','AGOSTO','SETIEMBRE','OCTUBRE','NOVIEMBRE','DICIEMBRE'];
const names={monthly:'Utilidad conciliada',service:'Servicios',expense_group:'Gastos por grupo',admin:'Administrativos',invoice:'Facturas y cobros',fuel:'Consumo',payable:'Deudas a terceros',original:'Todas las celdas'};
let sheetTitle='SETIEMBRE',kind='monthly',query='';
const sum=(rs,k)=>rs.reduce((s,r)=>s+Number(r[k]||0),0);
const tbl=(heads,rows)=>'<div class="table-wrap"><table><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
const card=(label,value)=>'<div class="metric"><small>'+esc(label)+'</small><strong>'+value+'</strong></div>';
const col=i=>{let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s;};
export function pendingHistoryView(data,month){
 const rows=(data.history_records||[]).filter(r=>r.kind==='service'&&r.data.review_status==='pending_settlement'&&(!month||r.data.date?.startsWith(month)));
 if(!rows.length)return '';
 return '<section class="notice"><h2>Viajes del histórico pendientes de liquidar</h2><p>Falta completar combustible y confirmar los demás gastos. Su resultado es provisional. Estos registros todavía son de consulta; su traslado a viajes editables está pendiente.</p>'+tbl(['Unidad','Fecha','Ruta','Servicio','Gastos registrados','Estado'],rows.map(r=>[esc(r.data.plate),esc(r.data.date),esc(r.data.origin+' → '+r.data.destination),money(r.data.total),money(r.data.recorded_expenses),'Pendiente de liquidar']))+'</section>';
}
export function historyView(data){
 const sheets=data.history_sheets||[],all=data.history_records||[];
 if(!sheets.length)return '<h1>Histórico del Sheets</h1><p>El historial real se consulta al ingresar con una cuenta autorizada de MT.</p>';
 const sheet=sheets.find(s=>s.title===sheetTitle)||sheets[0];sheetTitle=sheet.title;
 const rows=all.filter(r=>r.sheet_id===sheet.id&&r.kind===kind).filter(r=>!query||JSON.stringify(r.data).toLowerCase().includes(query.toLowerCase()));
 const issues=all.filter(r=>r.sheet_id===sheet.id&&r.data.issue);
 const review=issues.length?'<section class="notice"><h2>Pendientes de revisión</h2>'+tbl(['Referencia','Observación'],issues.map(r=>[esc(sheet.title+' · fila '+r.source_row),esc(r.data.issue)]))+'</section>':'';
 let body='';
 if(kind==='monthly'){
  const m=all.find(r=>r.sheet_id===sheet.id&&r.kind==='monthly')?.data;
  body=m?'<div class="metrics">'+card('Servicios',money(m.services))+card('Gastos de viajes',money(m.travel_expenses))+card('Gastos administrativos',money(m.administrative))+card('Utilidad del mes',money(m.recomputed_profit))+'</div><section class="card"><h2>Conciliación con el archivo</h2>'+tbl(['Concepto','Monto'],[['Servicios',money(m.services)],['Gastos de viajes',money(m.travel_expenses)],['Administrativos',money(m.administrative)],['Otros resultados: producción / embarques',money(m.other_result)],['Utilidad recalculada',money(m.recomputed_profit)],['Utilidad del Sheets',money(m.source_profit)],['Diferencia',money(m.difference)]])+'<p class="muted">Se conserva el criterio y precisión del libro. Las detracciones que el archivo descontaba como gasto siguen identificadas en su detalle histórico.</p></section>':'<p>Esta pestaña no contiene un cierre mensual.</p>';
 }else if(kind==='original'){
  const cs=[];sheet.rows.forEach((r,i)=>r.forEach((v,j)=>{const c=sheet.cells[`${i+1}:${j+1}`];if(v!==''&&v!==null||c?.input||c?.note){const addr=col(j)+(i+1),formula=c?.input?.formulaValue||'';if(!query||[addr,String(v),formula,c?.note||''].join(' ').toLowerCase().includes(query.toLowerCase()))cs.push([esc(addr),esc(v),esc(formula),esc(c?.note||'')]);}}));
  body='<p>'+cs.length+' celdas con información. Incluye fórmulas y notas del origen.</p>'+tbl(['Celda','Valor del archivo','Fórmula original','Nota'],cs);
 }else if(kind==='expense_group')body=tbl(['Origen','Unidad','Periodo','Total','Servicios vinculados','Detalle'],rows.map(r=>{const d=r.data;return[esc(sheet.title+' · fila '+r.source_row),esc(d.plate),esc((d.start_date||'Sin fecha')+' → '+(d.end_date||'Sin fecha')),money(d.total),esc(d.service_refs.map(s=>s.column+s.row).join(', ')||'Por revisar'),'<details><summary>Ver '+d.entries.length+' gastos</summary>'+d.entries.map(e=>'<p>'+esc(e.concept)+': '+money(e.amount)+'</p>').join('')+'</details>'];}));
 else if(kind==='service')body=tbl(['Fila','Fecha','Unidad','Cliente','Ruta','Subtotal','IGV','Total'],rows.map(r=>{const d=r.data;return[r.source_row,esc(d.date||'Por revisar'),esc(d.plate),esc(d.client),esc(d.origin+' → '+d.destination),money(d.subtotal),money(d.tax),money(d.total)];}));
 else if(kind==='invoice')body=tbl(['Fila','Fecha','Cliente','Unidad','Factura','Total','Detracción','Importe a cobrar','Estado en el archivo','Cancelación'],rows.map(r=>{const d=r.data;return[r.source_row,esc(d.date),esc(d.client),esc(d.plate||'No indicada'),esc(d.invoice||'Por emitir'),money(d.total),money(d.detraction),money(d.collectible),d.paid?'Pagada':'Pendiente según origen',esc(d.paid_on||'—')];}));
 else if(kind==='admin')body=tbl(['Fila','Concepto','Importe','Fecha individual'],rows.map(r=>[r.source_row,esc(r.data.concept),money(r.data.amount),'No indicada: gasto mensual']));
 else if(kind==='fuel')body=tbl(['Fila','Fecha','Unidad','Km inicial','Km final','Galones','Costo','Km/gl','Nota / factura'],rows.map(r=>{const d=r.data;return[r.source_row,esc(d.date||'No indicada'),esc(d.plate),d.odometer_start,d.odometer_end,d.gallons,money(d.amount),d.km_per_gallon?.toFixed(3)||'Revisar kilometraje',esc([d.receipt,d.invoice].filter(Boolean).join(' / '))];}));
 else if(kind==='payable')body=tbl(['Fila','Fecha','Concepto','Importe'],rows.map(r=>[r.source_row,esc(r.data.date||'No indicada'),esc(r.data.concept),money(r.data.amount)]));
 return '<h1>Histórico del Sheets</h1><p class="muted">'+sheets.length+' pestañas conservadas con sus valores, fórmulas y referencias. Los saldos de meses distintos son estados históricos y no se suman entre sí.</p><div class="actions"><label>Pestaña<select id="history-sheet">'+sheets.slice().sort((a,b)=>a.position-b.position).map(s=>'<option '+(s.title===sheetTitle?'selected':'')+'>'+esc(s.title)+'</option>').join('')+'</select></label><label>Ver<select id="history-kind">'+Object.entries(names).map(([k,n])=>'<option value="'+k+'" '+(kind===k?'selected':'')+'>'+n+'</option>').join('')+'</select></label><label>Buscar<input id="history-query" value="'+esc(query)+'" placeholder="Cliente, placa o celda"><button id="history-search">Buscar</button></label></div><br>'+review+body;
}
export function bindHistory(render){document.querySelector('#history-sheet')?.addEventListener('change',e=>{sheetTitle=e.target.value;if(sheetTitle==='Consumo')kind='fuel';else if(['Peajes','COBROS PENDIENTES'].includes(sheetTitle))kind='original';render();});document.querySelector('#history-kind')?.addEventListener('change',e=>{kind=e.target.value;render();});document.querySelector('#history-search')?.addEventListener('click',()=>{query=document.querySelector('#history-query').value;render();});}
export function adminView(data,month){const rows=(data.administrative_expenses||[]).filter(e=>!month||e.incurred_on.startsWith(month));return '<h1>Gastos administrativos</h1><p class="muted">Fecha del gasto, concepto e importe. Los pagos de facturas y deudas no se registran otra vez como gasto.</p><div class="actions"><label>Mes<input id="month" type="month" value="'+month+'"></label><button class="primary" data-action="admin">+ Registrar gasto administrativo</button></div><br>'+card('Nuevos gastos del mes',money(sum(rows,'amount')))+'<br>'+tbl(['Fecha','Categoría','Concepto','Importe'],rows.map(r=>[esc(r.incurred_on),esc(r.category),esc(r.description),money(r.amount)]))+'<p class="notice">Los 78 conceptos administrativos importados se consultan en Histórico. Ya están descontados en la utilidad conciliada y no debes registrarlos nuevamente.</p>';}
export function profitView(data,month){
 const title=months[Number(month.slice(5,7))-1],hist=month.startsWith('2026-')?(data.history_records||[]).find(r=>r.kind==='monthly'&&r.data.period===title)?.data:null;
 const ts=data.trips.filter(t=>!month||t.start_date.startsWith(month)),ex=data.expenses.filter(e=>!month||e.occurred_at.startsWith(month)),ad=(data.administrative_expenses||[]).filter(e=>!month||e.incurred_on.startsWith(month));
 const total=t=>Number(t.total??amounts(t.subtotal,t.tax_rate,'subtotal').total);
 const newIncome=ts.reduce((s,t)=>s+total(t),0),newCosts=sum(ex,'amount'),admin=sum(ad,'amount');
 const result=(hist?.recomputed_profit||0)+newIncome-newCosts-admin;
 const dates=[...new Set([...ts.map(t=>t.start_date),...ex.map(e=>e.occurred_at.slice(0,10)),...ad.map(e=>e.incurred_on)])].sort();let cumulative=0;
 const daily=dates.map(d=>{const income=ts.filter(t=>t.start_date===d).reduce((s,t)=>s+total(t),0),cost=sum(ex.filter(e=>e.occurred_at.startsWith(d)),'amount'),overhead=sum(ad.filter(e=>e.incurred_on===d),'amount');cumulative+=income-cost-overhead;return[esc(d),money(income),money(cost),money(overhead),money(income-cost-overhead),money(cumulative)];});
 return pendingHistoryView(data,month)+'<h1>Utilidad de la empresa</h1><p class="muted">Servicios − gastos de viajes − administrativos + otros resultados históricos. Los cobros y adelantos no se suman nuevamente como ingresos.</p><label>Mes<input id="month" class="filter" type="month" value="'+month+'"></label><br><div class="metrics">'+card('Servicios',money((hist?.services||0)+newIncome))+card('Gastos de viajes',money((hist?.travel_expenses||0)+newCosts))+card('Administrativos',money((hist?.administrative||0)+admin))+card('Utilidad provisional',money(result))+'</div>'+(hist?'<div class="notice">El cierre histórico aporta '+money(hist.recomputed_profit)+', incluidos '+money(hist.other_result)+' de otros resultados. Coincide con el Sheets. El detalle diario histórico está pendiente de fechar gastos mensuales y distribuir gastos compartidos; no se inventaron fechas.</div>':'')+'<section class="card"><h2>Movimiento diario registrado en la web</h2><p class="muted">Ingresos por fecha de servicio y gastos por su fecha de registro económico. El acumulado de esta tabla corresponde a los registros nuevos; los viajes abiertos son provisionales.</p>'+tbl(['Día','Servicios','Gastos de viajes','Administrativos','Resultado del día','Acumulado nuevo'],daily)+'</section>';
}
