import {payableRows} from './balances.js?v=20261001ze';
import {maintenanceFields,maintenanceValue,showMaintenance,linkedMaintenanceTable} from './maintenance-link.js?v=20261001ze';
import {money,round,amounts,fuelRows} from './domain.js?v=20261001ze';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const sum=(a,k)=>a.reduce((s,r)=>s+Number(r[k]||0),0);
export const table=(hs,rs)=>'<div class="table-wrap"><table><thead><tr>'+hs.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rs.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
export const card=(l,v)=>'<div class="metric"><small>'+esc(l)+'</small><strong>'+v+'</strong></div>';
export const tripMonth=t=>(t.accounting_month||t.start_date||'').slice(0,7);
export function allExpenses(d){return [...d.expenses,...(d.trip_cost_allocations||[]).filter(a=>Number(a.amount)>0).map(a=>{const c=d.trip_costs.find(c=>c.id===a.cost_id);return {...a,id:'cost-'+a.id,cost_id:c.id,category:c.category,description:c.description,occurred_at:c.occurred_on,payment_mode:'unconfirmed'};})];}
export function sharedCosts(d,trip){return d.trip_cost_links.filter(l=>l.trip_id===trip).map(l=>d.trip_costs.find(c=>c.id===l.cost_id)).filter(Boolean).map(c=>({...c,assigned:sum(d.trip_cost_allocations.filter(a=>a.cost_id===c.id),'amount'),own:sum(d.trip_cost_allocations.filter(a=>a.cost_id===c.id&&a.trip_id===trip),'amount'),count:d.trip_cost_links.filter(l=>l.cost_id===c.id).length}));}
export function costPanel(d,trip){const cs=sharedCosts(d,trip);if(!cs.length)return '';return '<section class="card"><h2>Gastos que corresponden a este viaje</h2><p class="muted">Cada importe compartido se asigna manualmente. El saldo sin repartir no se incluye todavía en la ganancia individual.</p>'+table(['Concepto','Total del gasto','Este viaje','Falta repartir',''],cs.map(c=>[esc(c.description),money(c.amount),money(c.own),money(Math.max(0,c.amount-c.assigned)),'<button data-edit-cost="'+c.id+'">Editar gasto</button> '+(c.count>1?'<button data-assign-cost="'+c.id+'" data-trip="'+trip+'">Asignar a este viaje</button>':'')]))+'</section>';}
export function adminPage(d,month){const rows=d.administrative_expenses.filter(e=>!e.archived_at&&(!month||e.period?.startsWith(month)));return '<h1>Gastos de la empresa</h1><p class="muted">Registra un concepto y desglosa sus importes por unidad o conductor.</p><div class="actions"><label>Mes<input type="month" id="month" value="'+esc(month)+'"></label><button class="primary" data-new-admin>+ Registrar gasto de empresa</button></div><br><div class="metrics">'+card('Total de gastos',money(sum(rows,'amount')))+card('Conceptos',rows.length)+'</div><section class="card"><h2>Detalle de gastos</h2>'+table(['Fecha / periodo','Concepto','Importe',''],rows.map(e=>[esc(e.incurred_on||e.period?.slice(0,7)+' · mensual'),esc(e.description),money(e.amount),'<button '+(d.maintenance_records.some(m=>m.expense_id===e.id)?'data-edit-maintenance="'+d.maintenance_records.find(m=>m.expense_id===e.id).id:'data-edit-admin="'+e.id)+'">Ver detalle / editar</button> <button class="danger" data-archive-admin="'+e.id+'">Eliminar</button>']))+(!rows.length?'<p class="empty">No hay gastos en este periodo.</p>':'')+'</section><details class="card"><summary>Gastos eliminados · recuperar</summary>'+table(['Concepto','Importe',''],d.administrative_expenses.filter(e=>e.archived_at&&(!month||e.period?.startsWith(month))).map(e=>[esc(e.description),money(e.amount),'<button data-restore-admin="'+e.id+'">Recuperar</button>']))+'</details>';}
export function payablePage(d){const rows=payableRows(d);return '<div class="page-head"><div><h1>Por pagar</h1><p class="muted">Combustible, terceros y subcontrataciones pendientes de pago.</p></div><button class="primary" data-new-debt>+ Agregar deuda</button></div><div class="metrics">'+card('Total pendiente',money(rows.reduce((s,e)=>s+Number(e.amount)-e.paid,0)))+card('Pagado',money(sum(rows,'paid')))+card('Deudas pendientes',rows.filter(e=>e.amount>e.paid).length)+'</div><p class="notice">Los gastos a crédito del viaje aparecen automáticamente. Agrega aquí únicamente deudas que no estén registradas; registrar o pagar una deuda no vuelve a descontar el gasto de la utilidad.</p><section class="card">'+table(['Fecha','Proveedor','Concepto','Placa','Importe','Pagado','Saldo',''],rows.map(e=>[esc(e.incurred_on),esc(e.supplier),esc(e.concept),esc(d.vehicles.find(v=>v.id===e.vehicle_id)?.plate||'General'),money(e.amount),money(e.paid),money(e.amount-e.paid),e.trip_id?e.round_id?'<button data-round="'+e.round_id+'">Ver vuelta</button>':'<button data-open="'+e.trip_id+'">Ver viaje</button>':'<button data-edit-debt="'+e.id+'">Editar</button> <button data-pay-debt="'+e.id+'">Registrar pago</button>']))+(!rows.length?'<p class="empty">Agrega tu primera deuda para ver el saldo.</p>':'')+'</section>';}
export function fuelPage(d,month){const fresh=fuelRows(d.expenses,d.trips,d.rounds).map(e=>({...e,date:e.occurred_at.slice(0,10)}));const previous=d.fuel_observations.map(e=>{const distance=e.odometer!==null&&e.previous_odometer!==null&&Number(e.odometer)>=Number(e.previous_odometer)?Number(e.odometer)-Number(e.previous_odometer):null;return {...e,date:e.occurred_on,distance,interval_ratio:distance!==null&&e.gallons>0?distance/e.gallons:null,price_per_gallon:e.gallons>0&&e.amount!==null?e.amount/e.gallons:null,observation:true};});const rows=[...previous,...fresh].filter(e=>!month||e.date?.startsWith(month)).sort((a,b)=>(b.date||'').localeCompare(a.date||''));return '<h1>Control de combustible</h1><label>Mes<input id="month" type="month" value="'+esc(month)+'"></label><p class="notice">Precio por galón = importe ÷ galones. Rendimiento del intervalo = kilómetros recorridos ÷ galones. El rendimiento entre tanques llenos requiere confirmar ambos llenados. Un kilometraje inconsistente se muestra para revisión.</p><div class="metrics">'+card('Abastecimientos',rows.length)+card('Galones',sum(rows,'gallons').toFixed(3))+'</div><section class="card"><h2>Cargas de combustible</h2>'+table(['Fecha','Unidad','Kilometraje','Km recorridos','Galones','S/ por galón','Km por galón (referencia)','Km por galón (tanques llenos)',''],rows.map(e=>[esc(e.date),esc(d.vehicles.find(v=>v.id===e.vehicle_id)?.plate),esc(e.odometer??'Por completar'),e.distance===null?'Revisar':esc(round(e.distance,1)),esc(e.gallons??'Por completar'),e.price_per_gallon===null?'—':money(e.price_per_gallon),e.interval_ratio===null?'—':round(e.interval_ratio,3),e.efficiency?round(e.efficiency,3):'Sin ciclo confirmado',e.observation?'<button data-edit-fuel="'+e.id+'">Ver / editar</button>':'<button data-open="'+e.trip_id+'">Ver viaje</button>']))+'</section>';}
export function resultData(d,month){const names=['ENERO','FEBRERO','MARZO','ABRIL','MAYO','JUNIO','JULIO','AGOSTO','SETIEMBRE','OCTUBRE','NOVIEMBRE','DICIEMBRE'];const closing=month?.startsWith('2026-')?d.history_records.find(r=>r.kind==='monthly'&&r.data.period===names[+month.slice(5,7)-1])?.data:null;
 const ts=d.trips.filter(t=>!month||tripMonth(t)===month);const incomes=ts.reduce((s,t)=>s+amounts(t.subtotal,t.tax_rate,'subtotal').total-(closing?Number(t.baseline_total||0):0),0)+(closing?.services||0);
 const newExpenses=d.expenses.filter(e=>!month||e.occurred_at?.startsWith(month));const costs=d.trip_costs.filter(e=>!month||e.period.startsWith(month));
 const expenses=(closing?.travel_expenses||0)+sum(newExpenses,'amount')+costs.reduce((s,c)=>s+Number(c.amount)-(closing?Number(c.baseline_amount):0),0);
 const admins=d.administrative_expenses.filter(e=>!e.archived_at&&(!month||e.period?.startsWith(month)));const administrative=sum(admins,'amount');const other=closing?.other_result||0;
 return {trips:ts,incomes,expenses,administrative,other,result:incomes-expenses-administrative+other};
}
export function profitPage(d,month,embedded=false){const r=resultData(d,month);const content='<h1>Ganancia de la empresa</h1><label>Mes<input id="month" type="month" value="'+esc(month)+'"></label><br><div class="metrics">'+card('Total por los viajes',money(r.incomes))+card('Gastos de viajes',money(r.expenses))+card('Gastos de empresa',money(r.administrative))+card('Ganancia provisional',money(r.result))+'</div><p class="notice">La utilidad se actualiza al editar gastos. Los abonos y pagos de deudas no se cuentan otra vez como ingresos o gastos. Los viajes pendientes de liquidar pueden cambiar este resultado.</p>'+(r.other?'<p>Otros resultados del mes: '+money(r.other)+'</p>':'');return embedded?'<section class="card"><h2>Ganancia de la empresa</h2><p class="muted">'+(month?'Mes '+esc(month):'Todos los meses')+' · Incluye todas las unidades y choferes.</p>'+content.slice(content.indexOf('<div class="metrics">'))+'</section>':content;}
export function installEditors(ctx){const {data,form,input,select,write,rpc,render,selected}=ctx;
 const options=(rs,label)=>rs.map(r=>[r.id,r[label]]);
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=data();
 if(b.dataset.archiveAdmin||b.dataset.restoreAdmin){const id=b.dataset.archiveAdmin||b.dataset.restoreAdmin,a=d.administrative_expenses.find(e=>e.id===id),archived=!!b.dataset.archiveAdmin;form(archived?'Eliminar gasto de empresa':'Recuperar gasto','<p class="notice full">'+esc(a.description)+' · '+money(a.amount)+'. '+(archived?'Dejará de contar en la utilidad y en mantenimiento. Podrás recuperarlo desde Gastos eliminados.':'Volverá a incluirse en la utilidad y en mantenimiento.')+'</p>',()=>rpc('mt_archive_admin',{p_id:id,p_archived:archived}));}
 if(b.hasAttribute('data-new-maintenance')||b.dataset.editMaintenance){const m=d.maintenance_records.find(x=>x.id===b.dataset.editMaintenance);const pieces=[...new Set(['Cardán','Motor','Caja de cambios','Frenos','Llantas','Suspensión','Sistema eléctrico',...d.maintenance_records.map(x=>x.component)])];form(m?'Editar mantenimiento':'Registrar falla / reparación',select('Unidad','vehicle',[...options(d.vehicles,'plate')],m?.vehicle_id||d.vehicles[0]?.id)+select('Tipo','kind',['Reparación','Compra de repuesto','Mantenimiento'].map(x=>[x,x]),m?.kind||'Reparación')+input('Pieza o sistema (puedes agregar uno nuevo)','component','text',m?.component||'','required list="components"')+'<datalist id="components">'+pieces.map(x=>'<option value="'+esc(x)+'">').join('')+'</datalist>'+select('Estado','status',[['Pendiente','Pendiente'],['Completado','Completado']],m?.status||'Pendiente')+input('Fecha de falla','failure','date',m?.failure_on||ctx.today())+input('Fecha de reparación / compra','service','date',m?.serviced_on||'')+input('Taller / lugar / proveedor','workshop','text',m?.workshop||'')+input('Trabajo realizado / observaciones','description','text',m?.description||'','required')+input('Costo total','amount','number',m?.amount||0,'min="0" step="0.01" required')+'<p class="notice full">El costo se registra automáticamente en Gastos de la empresa. No lo vuelvas a ingresar como otro gasto.</p>',v=>rpc('mt_save_maintenance',{p_id:m?.id||null,p_vehicle:v.vehicle,p_component:v.component,p_kind:v.kind,p_failure:v.failure||null,p_service:v.service||null,p_status:v.status,p_workshop:v.workshop,p_description:v.description,p_amount:Number(v.amount)}));}
 if(b.hasAttribute('data-edit-trip')){const t=d.trips.find(t=>t.id===b.dataset.editTrip);form('Editar servicio',input('Fecha de salida','start_date','date',t.start_date,'required')+input('Cliente','client','text',d.clients.find(c=>c.id===t.client_id)?.name,'required')+input('Origen','origin','text',t.origin,'required')+input('Destino','destination','text',t.destination,'required')+select('Chofer','driver_id',[['','Por confirmar'],...options(d.drivers,'name')],t.driver_id||'')+input('Total del servicio','value','number',amounts(t.subtotal,t.tax_rate,'subtotal').total,'step="0.01" min="0.01" required')+select('IGV','rate',[['18','18 %'],['0','0 %']],String(t.tax_rate)),async f=>{let c=d.clients.find(c=>c.name.trim().toLowerCase()===f.client.trim().toLowerCase());if(!c)c=await write('clients',{name:f.client.trim()});await write('trips',{client_id:c.id,start_date:f.start_date,origin:f.origin,destination:f.destination,driver_id:f.driver_id||null,subtotal:amounts(f.value,f.rate).subtotal,tax_rate:Number(f.rate)},t.id);});}
 if(b.dataset.editCost){const c=d.trip_costs.find(c=>c.id===b.dataset.editCost);form('Editar gasto: '+c.description,input('Importe total del gasto','amount','number',c.amount,'min="0" step="0.01" required')+input('Fecha individual (si la conoces)','date','date',c.occurred_on||'')+'<p class="notice full">Si el gasto es compartido, este total corresponde a todos los viajes asociados. Ajusta el reparto por separado.</p>',f=>rpc('mt_edit_cost',{p_cost:c.id,p_amount:Number(f.amount),p_date:f.date||null}));}
 if(b.dataset.assignCost){const c=d.trip_costs.find(c=>c.id===b.dataset.assignCost),t=b.dataset.trip,own=sum(d.trip_cost_allocations.filter(a=>a.cost_id===c.id&&a.trip_id===t),'amount');form('Asignar gasto a este viaje','<p class="notice full">Total del gasto: '+money(c.amount)+'. Asignado a otros viajes: '+money(sum(d.trip_cost_allocations.filter(a=>a.cost_id===c.id&&a.trip_id!==t),'amount'))+'</p>'+input('Importe que corresponde a este viaje','amount','number',own,'min="0" step="0.01" required'),f=>rpc('mt_assign_cost',{p_cost:c.id,p_trip:t,p_amount:Number(f.amount)}));}
 if(b.dataset.editFuel){const f=d.fuel_observations.find(f=>f.id===b.dataset.editFuel);form('Editar abastecimiento',select('Viaje asociado','trip',[['','Falta repartir'],...d.trips.filter(t=>t.vehicle_id===f.vehicle_id).map(t=>[t.id,t.start_date+' · '+t.origin+' → '+t.destination])],f.trip_id||'')+input('Fecha','date','date',f.occurred_on||'','required')+input('Kilometraje','odometer','number',f.odometer??'','min="0" step="0.1" required')+input('Galones','gallons','number',f.gallons??'','min="0.001" step="0.001" required')+'<p class="notice full">Este registro sirve para el rendimiento de la unidad. Su costo se revisa en los gastos del viaje; no se vuelve a sumar al asociarlo.</p>',v=>rpc('mt_edit_fuel',{p_id:f.id,p_trip:v.trip||null,p_date:v.date,p_odometer:Number(v.odometer),p_gallons:Number(v.gallons)}));}
 if(b.hasAttribute('data-new-admin')||b.dataset.editAdmin){const a=d.administrative_expenses.find(a=>a.id===b.dataset.editAdmin);let details=a?d.administrative_details.filter(x=>x.expense_id===a.id&&x.active):[];if(!details.length)details=[{description:a?.description||'',amount:a?.amount||'',vehicle_id:'',driver_id:''}];
 const row=(x,i)=>'<div class="card admin-line" data-line="'+i+'">'+select('Unidad','unit_'+i,[['','General / sin asignar'],...options(d.vehicles,'plate')],x.vehicle_id||'')+select('Conductor','driver_'+i,[['','No corresponde / por confirmar'],...options(d.drivers,'name')],x.driver_id||'')+input('Detalle adicional (opcional)','description_'+i,'text',x.description)+input('Importe','amount_'+i,'number',x.amount,'min="0.01" step="0.01" required')+maintenanceFields(input,x.maintenance,'m_'+i+'_',a?.incurred_on||'')+'<button type="button" data-remove-line>Quitar línea</button></div>';
 form(a?'Detalle / editar gasto':'Registrar gasto de empresa',input('Concepto','description','text',a?.description||'','required')+select('Categoría','category',['Sueldos','Seguros','GPS','Reparaciones','Repuestos','Oficina','Otros'].map(v=>[v,v]),a?.category||'Otros')+input('Fecha del gasto','date','date',a?a.incurred_on||'':ctx.today(),a&&!a.incurred_on?'':'required')+(a&&!a.incurred_on?'<p class="muted full">Fecha exacta por completar. Se conserva el mes registrado: '+esc(a.period.slice(0,7))+'.</p>':'')+'<div class="full" id="admin-lines">'+details.map(row).join('')+'</div><button class="full" type="button" id="add-admin-line">+ Agregar unidad / detalle</button><p class="notice full" id="admin-total"></p>',v=>{const items=[...document.querySelectorAll('.admin-line')].map(el=>{const i=el.dataset.line;return {description:v['description_'+i]?.trim()||v.description.trim(),amount:Number(v['amount_'+i]),vehicle_id:v['unit_'+i]||null,driver_id:v['driver_'+i]||null,maintenance:maintenanceValue(v,'m_'+i+'_',v.date)};});return rpc('mt_save_admin',{p_id:a?.id||null,p_description:v.description,p_category:v.category,p_period:v.date?v.date.slice(0,7)+'-01':a?.period,p_date:v.date||null,p_items:items});});
 const adminForm=document.querySelector('#modal form'),toggleMaintenance=()=>showMaintenance(adminForm,adminForm.elements.category.value);adminForm.elements.category.addEventListener('change',toggleMaintenance);toggleMaintenance();let index=details.length;const lines=document.querySelector('#admin-lines'),calc=()=>document.querySelector('#admin-total').textContent='Total: '+money([...lines.querySelectorAll('input[type=number]')].reduce((s,x)=>s+Number(x.value),0));document.querySelector('#add-admin-line').onclick=()=>{lines.insertAdjacentHTML('beforeend',row({description:'',amount:''},index++));toggleMaintenance();calc();};lines.addEventListener('input',calc);lines.addEventListener('click',e=>{if(e.target.closest('[data-remove-line]')){e.target.closest('.admin-line').remove();calc();}});calc();
 }
 if(b.hasAttribute('data-new-debt')||b.dataset.editDebt){const a=d.payable_accounts.find(a=>a.id===b.dataset.editDebt);form(a?'Editar deuda':'Agregar deuda',select('Concepto','concept',['Combustible','Pago a terceros','Subcontratación','Otros'].map(v=>[v,v]),a?.concept||'Combustible')+input('Proveedor / beneficiario','supplier','text',a?.supplier||'','required')+input('Fecha','incurred_on','date',a?.incurred_on||ctx.today(),'required')+input('Vencimiento','due_date','date',a?.due_date||'')+select('Placa de la unidad','vehicle_id',[['','General · sin unidad'],...options(d.vehicles,'plate')],a?.vehicle_id||'')+input('Monto de la deuda','amount','number',a?.amount||'','min="0.01" step="0.01" required')+input('Factura del proveedor (opcional)','invoice_number','text',a?.invoice_number||'')+input('Detalle','notes','text',a?.notes||''),v=>write('payable_accounts',{...v,vehicle_id:v.vehicle_id||null,due_date:v.due_date||null,amount:Number(v.amount)},a?.id));}
 if(b.dataset.payDebt){const a=d.payable_accounts.find(a=>a.id===b.dataset.payDebt),ps=d.payable_payments.filter(p=>p.account_id===a.id);form('Pagos a '+a.supplier,'<div class="full">'+table(['Fecha','Pago','Referencia'],ps.map(p=>[esc(p.paid_on),money(p.amount),esc(p.reference)]))+'<p>Saldo: '+money(a.amount-sum(ps,'amount'))+'</p></div>'+input('Fecha del pago','paid_on','date',ctx.today(),'required')+input('Importe del pago (puede ser parcial o total)','amount','number',Math.max(0,a.amount-sum(ps,'amount')),'min="0.01" max="'+Math.max(0,a.amount-sum(ps,'amount'))+'" step="0.01" required')+input('Referencia','reference'),v=>write('payable_payments',{...v,account_id:a.id,amount:Number(v.amount)}));}
 });
}
export function maintenancePage(d,vehicle=''){
 const rows=d.maintenance_records.filter(r=>(!vehicle||r.vehicle_id===vehicle)&&!d.administrative_expenses.find(e=>e.id===r.expense_id)?.archived_at).sort((a,b)=>(b.serviced_on||b.failure_on||'').localeCompare(a.serviced_on||a.failure_on||''));
 return '<div class="page-head"><div><h1>Mantenimiento</h1><p class="muted">Fallas, reparaciones y repuestos por unidad. Consulta las fechas anteriores antes de registrar un nuevo trabajo.</p></div><button class="primary" data-new-maintenance>+ Registrar falla / reparación</button></div><label>Unidad<select name="filter-vehicle"><option value="">Todas</option>'+d.vehicles.map(v=>'<option value="'+v.id+'" '+(vehicle===v.id?'selected':'')+'>'+esc(v.plate)+'</option>').join('')+'</select></label><br>'+linkedMaintenanceTable(d,vehicle,money,table)+'<section class="card"><h2>Fallas y trabajos registrados directamente</h2>'+table(['Unidad','Pieza / sistema','Falla','Reparación / compra','Trabajo / proveedor','Costo','Estado',''],rows.map(r=>[esc(d.vehicles.find(v=>v.id===r.vehicle_id)?.plate),esc(r.component),esc(r.failure_on||'—'),esc(r.serviced_on||'—'),esc(r.description)+'<br>'+esc(r.workshop||''),money(r.amount),esc(r.status),'<button data-edit-maintenance="'+r.id+'">Ver / editar</button>']))+(!rows.length?'<p class="empty">Aún no hay trabajos registrados para esta unidad.</p>':'')+'</section>';
}
