import {payableRows} from './balances.js?v=20261001ze';
import {money} from './domain.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let filter='pending';
export function paymentsPage(d,table){
 const all=payableRows(d),rows=all.filter(e=>filter==='paid'?Number(e.amount)-e.paid<=.005:Number(e.amount)-e.paid>.005);
 const payments=e=>d.payable_accounts.some(a=>a.id===e.id)?d.payable_payments.filter(p=>p.account_id===e.id):d.supplier_payments.filter(p=>p.expense_id===e.id);
 return '<div class="page-head"><div><h1>Pagos a proveedores</h1><p class="muted">Deudas pendientes y facturas que ya pagaste.</p></div><button class="primary" data-new-debt>+ Agregar deuda</button></div><div class="metrics"><div class="metric"><small>Por pagar</small><strong>'+money(all.reduce((s,e)=>s+Math.max(0,e.amount-e.paid),0))+'</strong></div><div class="metric"><small>Pagado</small><strong>'+money(all.reduce((s,e)=>s+e.paid,0))+'</strong></div></div><div class="tabs">'+[['pending','Pendientes'],['paid','Pagadas']].map(([k,v])=>'<button data-payments-filter="'+k+'" class="'+(filter===k?'active':'')+'">'+v+'</button>').join('')+'</div><p class="notice">Un gasto a crédito aparece automáticamente aquí. No vuelvas a agregarlo como deuda. Registrar el pago reduce la deuda; no descuenta otra vez la utilidad.</p><section class="card">'+table(['Fecha','Proveedor / concepto','Factura','Unidad','Importe','Pagado','Saldo','Último pago',''],rows.map(e=>[esc(e.incurred_on),esc(e.supplier)+'<p class="muted">'+esc(e.concept)+'</p>',esc(e.invoice_number||'Por completar'),esc(d.vehicles.find(v=>v.id===e.vehicle_id)?.plate||'General'),money(e.amount),money(e.paid),money(e.amount-e.paid),esc(payments(e).map(p=>p.paid_on).sort().at(-1)||'—'),'<button data-payment-history="'+e.id+'">Ver pagos</button> '+(filter==='pending'?(d.payable_accounts.some(a=>a.id===e.id)?'<button data-pay-debt="'+e.id+'">Registrar pago</button>':'<button data-supplier="'+e.id+'">Registrar pago</button>'):'')+(d.payable_accounts.some(a=>a.id===e.id)?' <button data-edit-debt="'+e.id+'">Editar</button>':'')]))+'</section>';
}
export function installPayments({data,render,form,table}){document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.paymentsFilter){filter=b.dataset.paymentsFilter;render();}if(b.dataset.paymentHistory){const d=data(),id=b.dataset.paymentHistory,a=d.payable_accounts.find(x=>x.id===id),rows=a?d.payable_payments.filter(p=>p.account_id===id):d.supplier_payments.filter(p=>p.expense_id===id);form('Historial de pagos','<div class="full">'+table(['Fecha','Monto','Medio','Operación'],rows.map(p=>[esc(p.paid_on),money(p.amount),esc(p.method||'—'),esc(p.reference||'—')]))+'</div>',async()=>{});}});}
