import {updateOwnPassword} from './account.js?v=20261001ze';
import {readResponse} from './http.js?v=20261001ze';
import {loginIdentity} from './auth-identity.js?v=20261001ze';
import {config} from '../config.js?v=20261001ze';
import {amounts,summarize} from './domain.js?v=20261005b';
import {separateDeleted} from './operation-trash.js?v=20261001zk';
const tables=['company_documents','rounds','driver_cash_entries','drivers','vehicles','clients','trips','expenses','customer_payments','supplier_payments','administrative_expenses','payable_accounts','payable_payments'];
const readTables=[...tables,'supplier_invoices','supplier_invoice_items','supplier_invoice_payments','deleted_operations','profiles','history_sheets','history_records','trip_costs','trip_cost_links','trip_cost_allocations','fuel_observations','administrative_details','maintenance_records'];
let session=readSession(sessionStorage);
const refreshSession=singleFlight(async()=>{const previous=session;try{const next=await authToken(config.url,config.key,'refresh_token',{refresh_token:previous.refresh_token});if(session!==previous)return;session=next;sessionStorage.setItem('mt-session',JSON.stringify(session));}catch(error){if(error.invalidSession&&session===previous)logout();throw error;}});
export const store={demo:false,data:{},user:null};
const save=()=>localStorage.setItem('mt-demo-v2',JSON.stringify(store.data));
export const login=singleFlight(async(email,password)=>{if(!config.key)throw Error('Falta configurar el acceso al sistema.');session=await authToken(config.url,config.key,'password',{email:loginIdentity(email),password});sessionStorage.setItem('mt-session',JSON.stringify(session));store.demo=false;store.user=null;store.data={};try{await load();}catch(error){if(!session)throw error;throw Error('Tu acceso fue validado, pero no se pudieron cargar los datos. Intenta ingresar nuevamente. '+error.message);}});
async function request(route,options={}){if(!session)throw Error('Tu sesión terminó. Vuelve a ingresar.');if(!Number.isFinite(session.expires_at)||session.expires_at<Date.now()/1000+60)await refreshSession();if(!session)throw Error('Tu sesión terminó. Vuelve a ingresar.');const r=await fetch(config.url+'/rest/v1/'+route,{...options,headers:{apikey:config.key,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json',Prefer:'return=representation',...options.headers}});return readResponse(r);}
export function logout(){session=null;sessionStorage.removeItem('mt-session');store.user=null;store.demo=false;store.data={};}
export async function load(){if(store.demo)return;const identity=session?.user?.id;if(!identity)throw Error('Vuelve a iniciar sesión.');const profile=await request('profiles?select=*&id=eq.'+identity);if(!profile?.[0]?.active){logout();throw Error('Esta cuenta aún no tiene un perfil autorizado en MT.');}const next={};for(const t of readTables){let all=[];for(let offset=0;;offset+=1000){const rows=await request(t+'?select=*&order=id&limit=1000&offset='+offset);if(!Array.isArray(rows))throw Error('No se pudieron cargar los datos. Intenta nuevamente.');all.push(...rows);if(rows.length<1000)break;}next[t]=all;}if(session?.user?.id!==identity)return;store.data=separateDeleted(next);store.user=profile[0];}
export async function restore(){if(session){await load();return true;}return false;}
export function demo(){store.demo=true;store.user={display_name:'Alex · ejemplo',role:'admin'};const saved=localStorage.getItem('mt-demo-v2');if(saved){store.data=JSON.parse(saved);store.data.administrative_expenses||=[];store.data.history_sheets||=[];store.data.history_records||=[];return;}const t={id:'trip-demo',number:1,vehicle_id:'f2h',client_id:'client-demo',start_date:'2026-09-29',origin:'Pisco',destination:'Chala',driver:'Chofer de ejemplo 1',driver_id:'joel',status:'in_progress',subtotal:amounts(4140).subtotal,tax_rate:18,detraction:0,invoice_status:'pending',created_at:'2026-09-29T08:00:00-05:00'};store.data={drivers:[{id:'joel',name:'Chofer de ejemplo 1',active:true},{id:'alonso',name:'Chofer de ejemplo 2',active:true}],vehicles:[{id:'a3k',plate:'A3K-853',description:'Volvo rojo',active:true,default_driver_id:'alonso'},{id:'f2h',plate:'F2H-732',description:'International blanco',active:true,default_driver_id:'joel'}],clients:[{id:'client-demo',name:'Cliente de ejemplo'}],trips:[t],expenses:[{id:'expense-demo',trip_id:t.id,occurred_at:'2026-09-29T10:00:00-05:00',category:'Combustible',amount:1500,payment_mode:'credit',supplier:'Grifo de ejemplo',odometer:680000,gallons:60,full_tank:true,created_at:'2026-09-29T10:00:00-05:00'}],customer_payments:[{id:'payment-demo',trip_id:t.id,paid_on:'2026-09-29',amount:1000,kind:'customer',method:'Transferencia',reference:'Adelanto de ejemplo'}],supplier_payments:[],administrative_expenses:[],history_sheets:[],history_records:[]};save();}
export async function write(table,values,id){if(!tables.includes(table))throw Error('Tabla no válida');if(!store.demo){const rows=await request(table+(id?'?id=eq.'+id:''),{method:id?'PATCH':'POST',body:JSON.stringify(values)});await load();return rows[0];}if(table==='administrative_expenses'&&(!(values.amount>0)||!values.description?.trim()))throw Error('Completa concepto e importe positivo.');const old=store.data[table].find(x=>x.id===id);const obj={...old,...values,id:id||crypto.randomUUID(),created_at:old?.created_at||new Date().toISOString()};const t=store.data.trips.find(x=>x.id===obj.trip_id);if(table==='expenses'){if(t?.settlement_status==='settled')throw Error('Reabre la liquidación antes de agregar gastos.');if(obj.amount<=0)throw Error('El importe debe ser mayor que cero.');if(obj.payment_mode==='credit'&&!obj.supplier?.trim())throw Error('Indica el proveedor.');if(obj.category==='Combustible'&&(!(obj.gallons>0)||!(obj.odometer>=0)))throw Error('Completa galones y kilometraje.');}
if(table==='customer_payments'){const s=summarize(t,store.data.expenses,store.data.customer_payments.filter(p=>p.id!==id));if(obj.amount<=0||obj.amount>(obj.kind==='detraction'?s.detraction_balance:s.customer_balance))throw Error('El pago supera el saldo o tiene un importe inválido.');}
if(table==='supplier_payments'){const e=store.data.expenses.find(e=>e.id===obj.expense_id);const paid=store.data.supplier_payments.filter(p=>p.expense_id===e.id&&p.id!==id).reduce((s,p)=>s+Number(p.amount),0);if(e.payment_mode!=='credit'||obj.amount<=0||obj.amount>e.amount-paid)throw Error('El pago supera el saldo del proveedor.');}
if(table==='trips'){obj.number=old?.number||Math.max(0,...store.data.trips.map(t=>t.number))+1;if(obj.end_date&&obj.end_date<obj.start_date)throw Error('El término no puede ser anterior al inicio.');if(obj.invoice_status==='issued'&&(!obj.invoice_number?.trim()||!obj.invoice_date))throw Error('Completa número y fecha de factura.');if(obj.invoice_number&&store.data.trips.some(t=>t.id!==id&&t.invoice_number?.trim().toLowerCase()===obj.invoice_number.trim().toLowerCase()))throw Error('Ese número de factura ya existe.');const s=summarize(obj,store.data.expenses,store.data.customer_payments);if(s.customer_balance<0||s.detraction_balance<0)throw Error('El importe contradice los pagos registrados.');}
if(id)store.data[table]=store.data[table].map(x=>x.id===id?obj:x);else store.data[table].push(obj);save();return obj;}

export async function rpc(name,args){if(store.demo)throw Error("Esta acción requiere ingresar con tu cuenta. La demostración no modifica datos reales.");const result=await request("rpc/"+name,{method:"POST",body:JSON.stringify(args)});await load();return result;}

export async function createUser(values){
 if(store.demo)throw Error('Ingresa con tu cuenta administradora para crear usuarios.');
 if(store.user?.role!=='admin')throw Error('Acceso reservado al administrador.');
 await request('profiles?select=id&limit=1');
 const r=await fetch(config.url+'/functions/v1/manage-users',{method:'POST',headers:{apikey:config.key,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify(values)});
 const result=await r.json();if(!r.ok)throw Error(result.message||'No se pudo crear el usuario.');await load();return result;
}

export async function changePassword(values){
 if(store.demo||!session?.user?.id)throw Error('Ingresa con tu cuenta para cambiar tu contraseña.');
 await updateOwnPassword({...values,url:config.url,key:config.key,userId:session.user.id,email:session.user.email});
 logout();
}
import {readSession,authToken,singleFlight} from './auth-session.js?v=20261001ze';
